-- ============================================================
-- SQL Migration: Add region to universities
-- ============================================================
ALTER TABLE universities ADD COLUMN IF NOT EXISTS region TEXT CHECK (region IN ('USA', 'Europe', 'Middle East', 'Asia')) DEFAULT 'USA';

-- ============================================================
-- Seed data for Extensive US Universities with Financial Aid
-- ============================================================

INSERT INTO universities (
  name, location, country, ranking_us_news, ranking_qs, acceptance_rate, 
  avg_sat, avg_act, avg_gpa, financial_aid_intl, need_blind_intl,
  culture_tags, strong_majors, region
) VALUES 
('Amherst College', 'MA', 'US', null, null, 8.5, 1540, 35, 4.0, true, true, '{"Private Liberal Arts"}', '{}', 'USA'),
('Bowdoin College', 'ME', 'US', null, null, 8.9, null, null, null, true, true, '{"Private Liberal Arts"}', '{}', 'USA'),
('Brown University', 'RI', 'US', null, 73, 5.5, 1535, 34, 4.0, true, true, '{"Private"}', '{}', 'USA'),
('Dartmouth College', 'NH', 'US', null, 237, 6.2, 1535, 34, 4.0, true, true, '{"Private"}', '{}', 'USA'),
('Harvard University', 'MA', 'US', 3, 4, 3.4, 1545, 34, 4.0, true, true, '{"Private"}', '{}', 'USA'),
('Massachusetts Institute of Technology', 'MA', 'US', 2, 1, 4.1, 1550, 35, 4.0, true, true, '{"Private"}', '{}', 'USA'),
('Princeton University', 'NJ', 'US', 1, 17, 4.4, 1530, 34, 4.0, true, true, '{"Private"}', '{}', 'USA'),
('University of Notre Dame', 'IN', 'US', null, null, 14.6, 1500, null, null, true, true, '{"Private"}', '{}', 'USA'),
('Yale University', 'CT', 'US', 5, 16, 4.6, 1520, 34, 4.0, true, true, '{"Private"}', '{}', 'USA'),
('Columbia University', 'NY', 'US', 12, 23, 3.9, 1535, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('Cornell University', 'NY', 'US', 13, 13, 8.7, 1535, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('Duke University', 'NC', 'US', 7, 57, 5.8, 1535, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('Stanford University', 'CA', 'US', 3, 3, 4.0, 1535, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('University of Pennsylvania', 'PA', 'US', 6, 12, 5.9, 1535, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('University of Chicago', 'IL', 'US', null, 11, 6.3, 1535, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('Northwestern University', 'IL', 'US', 9, 47, 6.8, 1540, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('Johns Hopkins University', 'MD', 'US', 9, 28, 7.5, 1545, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('California Institute of Technology', 'CA', 'US', null, null, 3.1, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Williams College', 'MA', 'US', 1, null, 8.5, 1535, 34, 4.0, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Swarthmore College', 'PA', 'US', 4, null, 7.5, 1540, 34, 4.0, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Wellesley College', 'MA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Wesleyan University', 'CT', 'US', null, null, 16.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Pomona College', 'CA', 'US', 4, null, 7.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Vassar College', 'NY', 'US', null, null, 19.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Smith College', 'MA', 'US', null, null, 22.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Colby College', 'ME', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Colgate University', 'NY', 'US', 21, null, 17.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Tufts University', 'MA', 'US', null, null, 10.8, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Haverford College', 'PA', 'US', null, null, 13.3, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Washington and Lee University', 'VA', 'US', null, null, 13.6, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Washington University in St. Louis', 'MO', 'US', 24, 154, 12.0, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Vanderbilt University', 'TN', 'US', 18, 262, 6.7, 1530, 34, 4.0, true, false, '{"Private"}', '{}', 'USA'),
('Georgetown University', 'DC', 'US', 22, 301, 12.0, 1450, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Carleton College', 'MN', 'US', null, null, 15.5, 1530, 34, 4.0, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Pitzer College', 'CA', 'US', null, null, 26.8, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Bates College', 'ME', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Barnard College', 'NY', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Berea College', 'KY', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Brandeis University', 'MA', 'US', null, null, null, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Bryn Mawr College', 'PA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Bucknell University', 'PA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Claremont McKenna College', 'CA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('College of Wooster', 'OH', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Davidson College', 'NC', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Emory University', 'GA', 'US', null, null, 13.0, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Franklin & Marshall College', 'PA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Gettysburg College', 'PA', 'US', null, null, 80.0, 1130, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Grinnell College', 'IA', 'US', null, null, 10.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Lafayette College', 'PA', 'US', null, null, 29.5, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Macalester College', 'MN', 'US', null, null, 29.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Reed College', 'OR', 'US', null, null, 25.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Rice University', 'TX', 'US', 17, 145, 9.5, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Trinity College', 'CT', 'US', null, null, 29.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Union College', 'NY', 'US', null, null, 44.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('University of Rochester', 'NY', 'US', null, null, 41.0, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Middlebury College', 'VT', 'US', null, null, 13.9, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Occidental College', 'CA', 'US', null, null, 44.9, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Scripps College', 'CA', 'US', null, null, 38.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Skidmore College', 'NY', 'US', null, null, 21.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Thomas Aquinas College', 'CA', 'US', null, null, 80.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('University of Richmond', 'VA', 'US', null, null, 22.0, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('University of Southern California', 'CA', 'US', null, null, 12.0, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Babson College', 'MA', 'US', null, null, null, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('College of the Holy Cross', 'MA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Colorado College', 'CO', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Connecticut College', 'CT', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Denison University', 'OH', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Hamilton College', 'NY', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Harvey Mudd College', 'CA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Kenyon College', 'OH', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Mount Holyoke College', 'MA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Oberlin College', 'OH', 'US', null, null, 34.0, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Providence College', 'RI', 'US', null, null, null, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Soka University of America', 'CA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Stetson University', 'FL', 'US', null, null, null, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('University of Tulsa', 'OK', 'US', null, null, null, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Bridgewater College', 'VA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Georgetown College', 'KY', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Saint Xavier University', 'IL', 'US', null, null, null, null, null, null, true, false, '{"Private"}', '{}', 'USA'),
('Dickinson College', 'PA', 'US', null, null, null, null, null, null, true, false, '{"Private Liberal Arts"}', '{}', 'USA'),
('Prairie View A&M', 'TX', 'US', null, null, 77.5, 940, null, 3.5, true, false, '{"Public"}', '{}', 'USA'),
('Alabama State Univ.', 'AL', 'US', null, null, 97.0, 859, null, 3.0, true, false, '{"Public"}', '{}', 'USA'),
('Troy University', 'AL', 'US', null, null, null, null, null, 3.7, true, false, '{"Public"}', '{}', 'USA'),
('Univ. of Southern Miss.', 'MS', 'US', null, null, null, 1420, null, 3.25, true, false, '{"Public"}', '{}', 'USA'),
('Mississippi State Univ.', 'MS', 'US', null, null, null, 1390, null, 4.1, true, false, '{"Public"}', '{}', 'USA'),
('University of Alabama', 'AL', 'US', null, null, 80.0, 1295, null, 3.5, true, false, '{"Public"}', '{}', 'USA'),
('Texas Tech University', 'TX', 'US', null, null, null, 1150, null, 3.0, true, false, '{"Public"}', '{}', 'USA'),
('Florida Gulf Coast Univ.', 'FL', 'US', null, null, null, 1135, null, 3.9, true, false, '{"Public"}', '{}', 'USA')
ON CONFLICT (name) DO UPDATE SET 
  region = EXCLUDED.region,
  acceptance_rate = EXCLUDED.acceptance_rate,
  avg_sat = EXCLUDED.avg_sat,
  avg_gpa = EXCLUDED.avg_gpa,
  need_blind_intl = EXCLUDED.need_blind_intl;
