import { ACTIVITY_DESCRIPTIONS, ACTIVITY_ICONS } from './activity-suggestions-shared';

type ActivitySuggestion = { name: string; type: string; emoji: string; desc: string; importance: string; tier: string; };

function hydrate(list: { n: string, i: string, t: string }[]): ActivitySuggestion[] {
    return list.map(item => ({
        name: item.n,
        type: ACTIVITY_ICONS[item.n as keyof typeof ACTIVITY_ICONS]?.type || "Other",
        emoji: ACTIVITY_ICONS[item.n as keyof typeof ACTIVITY_ICONS]?.emoji || "📌",
        desc: ACTIVITY_DESCRIPTIONS[item.n as keyof typeof ACTIVITY_DESCRIPTIONS] || "Explore and engage in this activity.",
        importance: item.i,
        tier: item.t
    }));
}

export const DATA_CHUNK_2: Record<string, ActivitySuggestion[]> = {
    "Journalism / Comms": hydrate([
        { n: "School Paper", i: "Proves deadline management, editing, and leadership.", t: "essential" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "essential" },
        { n: "Podcast", i: "Demonstrates modern multimedia storytelling capabilities.", t: "essential" },
        { n: "Philosophy Club", i: "Develops rigorous ethical and rhetorical frameworks.", t: "recommended" },
        { n: "Film Club", i: "Applies communication skills to digital broadcast media.", t: "recommended" },
        { n: "Broadcast TV", i: "Hones live-action reporting and studio coordination.", t: "recommended" },
        { n: "Media Camp", i: "Exposes student to rigorous, professional journalism.", t: "recommended" },
        { n: "E-Sports", i: "Shows modern digital strategy and livestreaming skills.", t: "recommended" },
        { n: "Social Media Mgr", i: "Applies communications theory to modern brand strategy.", t: "recommended" },
        { n: "Press Club", i: "Fosters peer review and journalistic integrity.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for data journalism.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis for science reporting.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to explain complex scientific variables.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad knowledge base useful for diverse reporting.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and narrative mapping.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and complex datasets.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical reporting cycles.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating international correspondence.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse, inclusive reporting.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and coordination.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and enunciation.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and broadcast presentation.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding and editorial illustration.", t: "recommended" },
        { n: "Photography", i: "Aids in photojournalism and visual story documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management and layout.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and creative non-fiction", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and informal networking.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and routine.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and local story sourcing.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and teamwork.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management reporting and safety.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and inventory management skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in high-stress sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and research archiving.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership and access to administrative policy.", t: "recommended" },
        { n: "Debate Team", i: "Essential for interview negotiation and cross-examination", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and international awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and communication.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting article pitching and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and clear communication.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable ESG reporting.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Music": hydrate([
        { n: "State Orchestra", i: "Validates elite technical skill and audition readiness.", t: "essential" },
        { n: "School Ensemble", i: "Shows daily discipline and collaborative musicality.", t: "essential" },
        { n: "Composition", i: "Demonstrates advanced grasp of musical theory and form.", t: "essential" },
        { n: "Tri-M Honor Soc", i: "Blends musical achievement with peer leadership.", t: "recommended" },
        { n: "Private Lessons", i: "Proves sustained, multi-year dedication to technique.", t: "recommended" },
        { n: "Community Choir", i: "Broadens repertoire and multi-generational collaboration.", t: "recommended" },
        { n: "Music Tutor", i: "Develops the pedagogical skills necessary for education.", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and fine motor coordination.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "recommended" },
        { n: "Philosophy Club", i: "Develops rigorous aesthetic and theoretical frameworks.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for advanced music theory", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and acoustics knowledge.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model sound waves and frequencies.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad knowledge base useful for music history.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and pattern recognition.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and complex datasets.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical musical eras.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for understanding global operatic traditions.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse ensemble environments.", t: "recommended" },
        { n: "Jazz Band", i: "Fosters improvisational discipline and syncopation.", t: "recommended" },
        { n: "Marching Band", i: "Proves physical stamina and complex marching coordination", t: "recommended" },
        { n: "Acapella Group", i: "Builds confident vocal harmony and pitch accuracy.", t: "recommended" },
        { n: "Drama Club", i: "Enhances stage presence and performative storytelling.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding and aesthetic sensibility.", t: "recommended" },
        { n: "Photography", i: "Aids in commercial visual marketing for musicians.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves lyrical songwriting and poetic phrasing.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local artistic events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and rhythm.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and breath control.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and teamwork.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and inventory management skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to provide music therapy in clinics.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and sheet music archiving.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future ensemble administration.", t: "recommended" },
        { n: "Debate Team", i: "Essential for contract negotiation and persuasion.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and ethnomusicology awareness", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and sales skills.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting gig generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable touring practices.", t: "recommended" },
        { n: "Peer Tutor (Gen)", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Education": hydrate([
        { n: "Baking Club", i: "Develops precise measurements and collaborative sharing.", t: "essential" },
        { n: "Camp Counselor", i: "Proves group management, patience, and youth engagement.", t: "essential" },
        { n: "Youth Mentor", i: "Shows long-term emotional investment in student success.", t: "essential" },
        { n: "Best Buddies", i: "Demonstrates deep empathy for diverse cognitive needs.", t: "recommended" },
        { n: "Sunday School", i: "Provides consistent, weekly instructional experience.", t: "recommended" },
        { n: "Coach", i: "Applies pedagogical principles to physical development.", t: "recommended" },
        { n: "Educators Rising", i: "Shows dedicated professional interest in the field.", t: "recommended" },
        { n: "Literacy Vol", i: "Addresses foundational learning gaps in the community.", t: "recommended" },
        { n: "Afterschool Prog", i: "Provides exposure to diverse, unstructured learning.", t: "recommended" },
        { n: "Lesson Planning", i: "Shows proactive curriculum design and organization.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for math education.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis for science teaching.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting variables.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and peer tutoring.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad knowledge base useful for general ed context", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and cognitive modeling.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and complex datasets.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical education policies.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating ESL/ELL classrooms.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse, inclusive classrooms.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and coordination.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and group harmony.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and classroom presentation skills", t: "recommended" },
        { n: "Art Club", i: "Develops creative visual aids and classroom aesthetics.", t: "recommended" },
        { n: "Photography", i: "Aids in commercial visual marketing and documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and editing skills.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local educational events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and routine.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and teamwork.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and school safety.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of food insecurity in students.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in high-stress sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and literacy advocacy.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future school administration.", t: "recommended" },
        { n: "Debate Team", i: "Essential for advocating for educational policy.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and cultural awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and communication.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds foundational child development understanding.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable campus initiatives.", t: "recommended" },
        { n: "Peer Tutor (Gen)", i: "Core pedagogical practice in academic subjects.", t: "recommended" }
    ]),
    "Physics": hydrate([
        { n: "Physics Bowl", i: "Validates elite grasp of theoretical physical mechanics.", t: "essential" },
        { n: "Physics Rsch", i: "Proves readiness for university-level experimental rigor.", t: "essential" },
        { n: "Baking Club", i: "Fosters precise procedural steps and fractional logic.", t: "essential" },
        { n: "Rocketry", i: "Applies Newtonian physics to physical engineering design.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and spatial navigation.", t: "recommended" },
        { n: "Philosophy Club", i: "Develops rigorous theoretical logic and quantum ethics.", t: "recommended" },
        { n: "Physics Tutor", i: "Shows ability to deconstruct complex mechanical theories.", t: "recommended" },
        { n: "Film Club", i: "Aids in visual storytelling for scientific concepts.", t: "recommended" },
        { n: "Quantum Camp", i: "Proves willingness to engage in intense, abstract study.", t: "recommended" },
        { n: "CAD Design", i: "Translates theoretical physics into spatial computer models", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for calculus/differential.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and collaborative logic.", t: "recommended" },
        { n: "Computer Coding", i: "Provides the computational skills needed for simulations.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall and diverse knowledge.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and spatial logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and orbital mechanics.", t: "recommended" },
        { n: "History Club", i: "Provides context for the history of scientific discovery.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for reading global physics publications.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse lab and academic teams.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and wave mechanics.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large structure.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and acoustic awareness.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and academic presentation skills", t: "recommended" },
        { n: "Art Club", i: "Develops creative geometric and spatial aesthetics.", t: "recommended" },
        { n: "Photography", i: "Aids in understanding optics, light, and lenses.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in writing scientific papers.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on technological events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and kinematics.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and geometric trajectory focus.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured kinetics.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and angular velocity focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible civil construction and physical effort.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and logistical optimization skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in complex facilities.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and research archiving.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future academic departments.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending scientific hypotheses and grants.", t: "recommended" },
        { n: "Model UN", i: "Fosters awareness of global infrastructure and science.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and communication.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting data generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and responsibility.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and interpersonal trust.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and physical work", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of atmospheric thermodynamics.", t: "recommended" },
        { n: "Peer Tutor (Gen)", i: "Proves ability to explain technical concepts simply.", t: "recommended" }
    ]),
    "Chemistry": hydrate([
        { n: "Chem Olympiad", i: "Serves as the ultimate benchmark for theoretical chem.", t: "essential" },
        { n: "Lab Intern", i: "Proves meticulous adherence to protocols and safety.", t: "essential" },
        { n: "ISEF Fair", i: "Highlights experimental design and independent discovery.", t: "essential" },
        { n: "Chem Club", i: "Fosters peer collaboration and passion for the subject.", t: "recommended" },
        { n: "Baking Club", i: "Fosters precise procedural measurements and fractional math", t: "recommended" },
        { n: "Water Testing", i: "Applies analytical chemistry to local ecological health.", t: "recommended" },
        { n: "Food Sci Proj", i: "Demonstrates a unique, applied niche within chemistry.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "recommended" },
        { n: "Pharmacy Shadow", i: "Provides realistic exposure to pharmacology and kinetics.", t: "recommended" },
        { n: "Materials Rsch", i: "Explores the physical properties of chemical bonds.", t: "recommended" },
        { n: "Math Team", i: "Validates the quantitative skills needed for stoichiometry", t: "recommended" },
        { n: "Science Olympiad", i: "Tests applied knowledge across various chemistry modules.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex thermodynamic systems.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall for complex nomenclature.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and diagnostic logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for astrochemistry and origins.", t: "recommended" },
        { n: "History Club", i: "Provides context for the history of scientific discovery.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for reading global chemical publications.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse lab and academic teams.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and procedural focus.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large system.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and breath mechanics.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking for scientific presentations.", t: "recommended" },
        { n: "Art Club", i: "Develops fine motor skills useful in precise titrations.", t: "recommended" },
        { n: "Photography", i: "Aids in microscopic and macroscopic visual documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in writing scientific abstracts.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local scientific events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and kinesiology.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and physiological endurance.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and biomechanical effort.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and quick reaction times.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and physical effort.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and hazmat awareness.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of nutrition and food preservation.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and basic biological care.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in clinical bio-environments", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity for research literature.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future lab management roles.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending scientific hypotheses and grants.", t: "recommended" },
        { n: "Model UN", i: "Fosters awareness of global chemical security and health.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and communication.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting data analysis and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and biological empathy.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and understanding of child safety.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and plant chem.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable bio-diversity.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to explain complex chemistry to peers.", t: "recommended" }
    ]),
    "International Relations": hydrate([
        { n: "Baking Club", i: "Fosters precise procedural steps and cultural sharing.", t: "essential" },
        { n: "Study Abroad", i: "Validates cross-cultural adaptability and global mindset.", t: "essential" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "essential" },
        { n: "Global NGO", i: "Applies IR theory to direct humanitarian intervention.", t: "recommended" },
        { n: "Philosophy Club", i: "Develops rigorous ethical and political frameworks.", t: "recommended" },
        { n: "Film Club", i: "Aids in global visual storytelling and documentaries.", t: "recommended" },
        { n: "Model Congress", i: "Shows understanding of domestic policy's global impact.", t: "recommended" },
        { n: "E-Sports", i: "Shows modern digital strategy and global communication.", t: "recommended" },
        { n: "Amnesty Int", i: "Connects local sociology to global human rights advocacy", t: "recommended" },
        { n: "Refugee Tutor", i: "Directly applies cross-cultural empathy and language.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for macroeconomics.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis for evidence-based policy.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting systems.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and civic reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad historical and geopolitical knowledge base.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and geopolitical logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and international space law.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical political cycles.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating international diplomacy.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for inclusive civic environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and civic ceremony.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection for public address.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and charismatic presentation.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding for political campaigns.", t: "recommended" },
        { n: "Photography", i: "Aids in photojournalism and geopolitical documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and speechwriting.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on global political events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and cultural routine", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and housing policy.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and international disaster.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of global social safety nets.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in public healthcare.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and community education.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future diplomatic administration.", t: "recommended" },
        { n: "Debate Team", i: "Essential for contract negotiation and policy debate.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and economic math awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and public relation.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable global climate policy", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Sociology": hydrate([
        { n: "Social Justice", i: "Shows commitment to systemic change and human rights.", t: "essential" },
        { n: "Demo Research", i: "Validates ability to analyze demographic and social data.", t: "essential" },
        { n: "Cultural Ldr", i: "Proves understanding of group dynamics and identities.", t: "essential" },
        { n: "Peer Mediation", i: "Applies sociological empathy to local conflict resolution", t: "recommended" },
        { n: "Community Outreach", i: "Engages directly with localized institutional structures.", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and informal social networking", t: "recommended" },
        { n: "ACLU", i: "Connects local sociology to legal civil rights advocacy.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "recommended" },
        { n: "Survey Proj", i: "Highlights the statistical side of sociological study.", t: "recommended" },
        { n: "Homeless Shelter", i: "Builds understanding of socioeconomic determinants.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for sociostatistics.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis for evidence-based policy.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting systems.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and civic reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad historical and sociological knowledge base.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and structural logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and scientific funding policy", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical societal shifts.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating intersectional demographics.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for inclusive civic environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and civic ceremony.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection for public address.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and charismatic presentation.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding for sociological campaigns.", t: "recommended" },
        { n: "Photography", i: "Aids in photojournalism and social documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and ethnography.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local social events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and cultural routine", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and housing policy.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and disaster sociology.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of social safety net logistics.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in public healthcare.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and community education.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future administrative roles.", t: "recommended" },
        { n: "Debate Team", i: "Essential for contract negotiation and policy debate.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and economic math awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and public relation.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable climate sociology.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Film / Media": hydrate([
        { n: "Film Club", i: "Proves collaborative storytelling and project management.", t: "essential" },
        { n: "Film Festivals", i: "Provides objective, external validation of creative vision", t: "essential" },
        { n: "Broadcast TV", i: "Builds technical skills in live production and editing.", t: "essential" },
        { n: "YouTube", i: "Shows self-directed audience building and digital media.", t: "recommended" },
        { n: "Stage Crew", i: "Applies lighting, sound, and blocking in a live setting.", t: "recommended" },
        { n: "Videography", i: "Demonstrates entrepreneurial and client-facing skills.", t: "recommended" },
        { n: "Scriptwriting", i: "Hones the foundational narrative structures of film.", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and informal networking.", t: "recommended" },
        { n: "Animation", i: "Demonstrates digital mastery and sequential narrative.", t: "recommended" },
        { n: "Media Intern", i: "Shows understanding of professional production studios.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor useful for budget management.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and optical science knowledge", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model light, shadow, and lenses.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad cultural knowledge base useful for writing.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and visual planning.", t: "recommended" },
        { n: "Astronomy Club", i: "Inspires aesthetic appreciation for scale and space.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for film history movements.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for understanding global cinema traditions.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability to design for diverse audiences.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and auditory art.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large ensemble.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and audio mixing logic.", t: "recommended" },
        { n: "Drama Club", i: "Enhances performative and visual storytelling skills.", t: "recommended" },
        { n: "Art Club", i: "Develops creative composition and aesthetic design.", t: "recommended" },
        { n: "Photography", i: "Foundational for framing, lighting, and cinematography.", t: "recommended" },
        { n: "Yearbook", i: "Provides applied layout, typography, and editing experience", t: "recommended" },
        { n: "Lit Mag", i: "Fuses visual illustration with scriptwriting.", t: "recommended" },
        { n: "School Paper", i: "Hones objective communication and editorial review.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates physical expression and kinetic blocking.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational teamwork.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and physical dedication.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and set design.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and visual organization skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and visual observation.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to bring art therapy to patients.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and respect for archives.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future creative direction.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending artistic choices and pitching.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and cultural awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and sales skills.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting video generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and creative play.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Inspires eco-friendly and sustainable media production.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to critique and guide peer portfolios.", t: "recommended" }
    ]),
    "Architecture": hydrate([
        { n: "Portfolio", i: "The critical metric of spatial and aesthetic reasoning.", t: "essential" },
        { n: "Baking Club", i: "Translates precise theoretical measurements into reality.", t: "essential" },
        { n: "Arch Summer Prog", i: "Exposes student to rigorous studio critique and design.", t: "essential" },
        { n: "Arch Club", i: "Fosters peer collaboration on spatial design challenges.", t: "recommended" },
        { n: "Design Comp", i: "Provides external validation of architectural concepts.", t: "recommended" },
        { n: "CAD", i: "Shows proactive interest in modern drafting technology.", t: "recommended" },
        { n: "Scouts", i: "Proves outdoor survival skills and structural building.", t: "recommended" },
        { n: "Philosophy Club", i: "Develops rigorous spatial and aesthetic philosophy.", t: "recommended" },
        { n: "Set Design", i: "Applies spatial design and collaborative construction.", t: "recommended" },
        { n: "Historic Preserv", i: "Fosters deep appreciation for architectural history.", t: "recommended" },
        { n: "Math Team", i: "Validates the structural and quantitative math required.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and material science.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model gravity, tension, and load.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad cultural knowledge base useful for context.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and spatial planning.", t: "recommended" },
        { n: "Astronomy Club", i: "Inspires aesthetic appreciation for scale and space.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for architectural movements.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for understanding global design traditions.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability to design for diverse audiences.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and spatial harmony.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large ensemble.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and acoustics.", t: "recommended" },
        { n: "Drama Club", i: "Enhances performative and visual storytelling skills.", t: "recommended" },
        { n: "Art Club", i: "Develops fine motor skills needed for drafting.", t: "recommended" },
        { n: "Photography", i: "Foundational for framing, lighting, and visual narrative.", t: "recommended" },
        { n: "Yearbook", i: "Provides applied layout, typography, and geometry.", t: "recommended" },
        { n: "Lit Mag", i: "Fuses visual illustration with creative structure.", t: "recommended" },
        { n: "School Paper", i: "Hones objective communication and editorial illustration.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates physical expression and spatial blocking.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational teamwork.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and physical dedication.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and spatial design.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and visual organization skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and visual observation.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to design for healthcare patients.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and respect for archives.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future creative direction.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending structural choices and bidding.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and urban planning awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and sales skills.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting design generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and creative play.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and landscaping.", t: "recommended" },
        { n: "Enviro Club", i: "Inspires eco-friendly and sustainable design materials.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to critique and guide peer portfolios.", t: "recommended" }
    ]),
    "Nursing": hydrate([
        { n: "CNA Cert", i: "Proves readiness for demanding, direct bedside care.", t: "essential" },
        { n: "HOSA", i: "Validates early, structured commitment to nursing skills.", t: "essential" },
        { n: "Baking Club", i: "Demonstrates proactive civic health and measurement math.", t: "essential" },
        { n: "EMT", i: "Shows ability to manage high-stress medical crises.", t: "recommended" },
        { n: "Scouts", i: "Highlights immense personal maturity and outdoor safety.", t: "recommended" },
        { n: "Special Needs Vol", i: "Builds patience and communication in complex care scenarios", t: "recommended" },
        { n: "Health Camp", i: "Shows leadership in preventative public health education.", t: "recommended" },
        { n: "Philosophy Club", i: "Validates the anatomical and bioethical science baseline.", t: "recommended" },
        { n: "Film Club", i: "Highlights ability to operate in health-media sectors.", t: "recommended" },
        { n: "Blood Drive", i: "Shows organizational capacity and clinical phlebotomy.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for pharmacology.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds broad, interdisciplinary scientific competence.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to grasp biophysical mechanisms.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall vital for diagnostics.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and diagnostic logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and the scientific method.", t: "recommended" },
        { n: "History Club", i: "Provides context for the evolution of public health.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for communicating with diverse patients.", t: "recommended" },
        { n: "Cultural Club", i: "Shows cultural competency for equitable healthcare.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and fine motor skills.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize and maintain focus.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and breath control.", t: "recommended" },
        { n: "Drama Club", i: "Enhances bedside manner and patient communication.", t: "recommended" },
        { n: "Art Club", i: "Develops fine motor skills useful in clinical contexts.", t: "recommended" },
        { n: "Photography", i: "Aids in visual observation and detail orientation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in clinical documentation.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on public health topics.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical stamina and coordination.", t: "recommended" },
        { n: "Varsity Soccer", i: "Demonstrates physical stamina needed for clinical work.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual perseverance through exhaustion.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and quick reaction times.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and continuous service.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible community care and physical effort.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and disaster triage.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of social determinants of health.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and basic biological care.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in clinical sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and record keeping.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future healthcare administration.", t: "recommended" },
        { n: "Debate Team", i: "Essential for advocating for patient care protocols.", t: "recommended" },
        { n: "Model UN", i: "Fosters awareness of global health initiatives (WHO).", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and empathy.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting work ethic and time management.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and personal maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and pediatric communication skills.", t: "recommended" },
        { n: "Lawn Care", i: "Shows independent hustle and physical endurance.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of environmental health impacts.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to explain diagnoses to patients clearly.", t: "recommended" }
    ])
};
