import { ACTIVITY_DESCRIPTIONS, ACTIVITY_ICONS } from './activity-suggestions-shared';

type ActivitySuggestion = { name: string; type: string; emoji: string; desc: string; importance: string; tier: string; };

function hydrate(list: { n: string, i: string, t: string }[]): ActivitySuggestion[] {
    return list.map(item => ({
        name: item.n,
        type: ACTIVITY_ICONS[item.n as keyof typeof ACTIVITY_ICONS]?.type || "Other",
        emoji: ACTIVITY_ICONS[item.n as keyof typeof ACTIVITY_ICONS]?.emoji || "📌",
        desc: ACTIVITY_DESCRIPTIONS[item.n as keyof typeof ACTIVITY_DESCRIPTIONS] || "Explore and engage in this activity.",
        importance: item.i,
        tier: item.t
    }));
}

export const DATA_CHUNK_1: Record<string, ActivitySuggestion[]> = {
    "Computer Science": hydrate([
        { n: "FIRST Robotics", i: "Proves applied coding and hardware integration.", t: "essential" },
        { n: "Regional Hackathon", i: "Demonstrates rapid problem-solving and collaboration.", t: "essential" },
        { n: "Open Source Contrib", i: "Shows real-world coding and team development.", t: "essential" },
        { n: "Personal App Dev", i: "Highlights self-driven innovation and product design.", t: "recommended" },
        { n: "Coding Club Founder", i: "Displays initiative, leadership, and mentorship.", t: "recommended" },
        { n: "USACO Competitor", i: "Validates elite algorithmic and mathematical thinking.", t: "recommended" },
        { n: "Tech Startup Intern", i: "Provides highly valued real-world industry exposure.", t: "recommended" },
        { n: "CyberPatriot", i: "Demonstrates vital cybersecurity and network skills.", t: "recommended" },
        { n: "NPO Webmaster", i: "Applies technical skills to civic digital infrastructure.", t: "recommended" },
        { n: "IT Volunteer", i: "Shows community dedication and tech troubleshooting.", t: "recommended" },
        { n: "Math Team", i: "Builds the algorithmic logic foundations required.", t: "recommended" },
        { n: "Science Olympiad", i: "Fosters interdisciplinary STEM logic and teamwork.", t: "recommended" },
        { n: "Physics Club", i: "Applies mathematical models to physical systems.", t: "recommended" },
        { n: "National Honor Soc", i: "Shows a high academic baseline and peer leadership.", t: "recommended" },
        { n: "Quiz Bowl", i: "Demonstrates rapid information recall under pressure.", t: "recommended" },
        { n: "Chess Club", i: "Proves advanced strategic and spatial logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows curiosity in complex, data-heavy systems.", t: "recommended" },
        { n: "History Club", i: "Provides societal context for tech evolution.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Aids in the cognitive flexibility of learning syntax.", t: "recommended" },
        { n: "Cultural Club", i: "Shows ability to work in global tech environments.", t: "recommended" },
        { n: "Band", i: "Builds discipline and complex pattern recognition.", t: "recommended" },
        { n: "Orchestra", i: "Fosters collaborative precision and timing.", t: "recommended" },
        { n: "Choir", i: "Shows teamwork and coordinated group focus.", t: "recommended" },
        { n: "Drama Club", i: "Builds public speaking skills vital for tech pitches.", t: "recommended" },
        { n: "Art Club", i: "Improves UI/UX design aesthetics and creativity.", t: "recommended" },
        { n: "Photography", i: "Aids in digital media processing and visual logic.", t: "recommended" },
        { n: "Yearbook", i: "Provides applied graphic design and layout experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves technical and narrative writing skills.", t: "recommended" },
        { n: "School Paper", i: "Hones clear, concise communication and editing.", t: "recommended" },
        { n: "Dance Team", i: "Builds physical discipline and spatial focus.", t: "recommended" },
        { n: "Varsity Soccer", i: "Shows teamwork vital for agile software development.", t: "recommended" },
        { n: "Track & Field", i: "Demonstrates individual perseverance and stamina.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic, independent focus and agility.", t: "recommended" },
        { n: "Key Club", i: "Shows civic duty and localized community care.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Applies spatial skills to real-world structures.", t: "recommended" },
        { n: "Red Cross", i: "Demonstrates organizational crisis management.", t: "recommended" },
        { n: "Food Bank", i: "Shows logistical organization and inventory skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Builds empathy and adherence to routine care.", t: "recommended" },
        { n: "Hospital Vol", i: "Exposes student to medical technology needs.", t: "recommended" },
        { n: "Library Vol", i: "Shows deep respect for information archiving systems.", t: "recommended" },
        { n: "Student Gov", i: "Builds tech leadership and policy understanding.", t: "recommended" },
        { n: "Debate Team", i: "Improves logical argumentation and structuring.", t: "recommended" },
        { n: "Model UN", i: "Fosters global tech policy and diplomatic awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds customer UX empathy and communication.", t: "recommended" },
        { n: "Freelance Coder", i: "Proves entrepreneurial drive and client management.", t: "recommended" },
        { n: "Family Care", i: "Shows immense maturity and time-balance capability.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and clear communication.", t: "recommended" },
        { n: "Lawn Care", i: "Shows an independent, self-starting work ethic.", t: "recommended" },
        { n: "Enviro Club", i: "Inspires green technology and sustainable solutions.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves the ability to explain complex code to novices.", t: "recommended" }
    ]),
    "Business / Economics": hydrate([
        { n: "DECA / FBLA", i: "Validates competitive business and marketing acumen.", t: "essential" },
        { n: "Startup Founder", i: "Shows pure entrepreneurial initiative and risk taking.", t: "essential" },
        { n: "Student Gov Treas", i: "Proves practical financial management and peer trust.", t: "essential" },
        { n: "Investment Club", i: "Demonstrates analytical market interest and research.", t: "recommended" },
        { n: "Econ Research", i: "Highlights deep analytical thinking on macro trends.", t: "recommended" },
        { n: "Local Biz Intern", i: "Gives real-world exposure to corporate operations.", t: "recommended" },
        { n: "School Store Mgr", i: "Proves applied inventory and retail management skills.", t: "recommended" },
        { n: "Microfinance Club", i: "Fuses economic principles with philanthropic impact.", t: "recommended" },
        { n: "Job Shadowing", i: "Demonstrates proactive career exploration.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and sales skills.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for advanced economics.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and collaborative logic.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting variables.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad knowledge base useful for market context.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and risk calculation.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and complex datasets.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical market cycles.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating international global markets.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse corporate environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and coordination.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and group harmony.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and pitch presentation skills.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding and marketing aesthetics.", t: "recommended" },
        { n: "Photography", i: "Aids in commercial visual marketing and advertising.", t: "recommended" },
        { n: "Yearbook", i: "Provides project management and budget experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and editing skills.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local economic events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and routine.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and teamwork.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and inventory management skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in high-stress sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and record keeping.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "recommended" },
        { n: "Debate Team", i: "Essential for contract negotiation and persuasion.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and economic awareness.", t: "recommended" },
        { n: "E-Sports", i: "Shows modern digital strategy and team coordination.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and sales.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable ESG business.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Medicine / Pre-Med": hydrate([
        { n: "Hospital Vol", i: "Shows profound empathy and clinical reality exposure.", t: "essential" },
        { n: "HOSA Participation", i: "Demonstrates a focused, early commitment to healthcare.", t: "essential" },
        { n: "Bio Research", i: "Proves high-level scientific inquiry and lab skills.", t: "essential" },
        { n: "EMT Certification", i: "Validates hands-on crisis management and medical care.", t: "recommended" },
        { n: "Doctor Shadowing", i: "Provides a realistic perspective of the profession.", t: "recommended" },
        { n: "Red Cross Club", i: "Shows proactive health advocacy and civic duty.", t: "recommended" },
        { n: "Science Fair", i: "Highlights experimental design and independent discovery.", t: "recommended" },
        { n: "Bio Olympiad", i: "Validates elite, competitive biological knowledge.", t: "recommended" },
        { n: "Caregiver", i: "Demonstrates profound maturity and sustained empathy.", t: "recommended" },
        { n: "Health Camp", i: "Exposes student to rigorous pre-medical coursework.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for pharmacology.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds broad, interdisciplinary scientific competence.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to grasp biophysical mechanisms.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall vital for diagnostics.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and diagnostic logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and the scientific method.", t: "recommended" },
        { n: "History Club", i: "Provides context for the evolution of public health.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for communicating with diverse patients.", t: "recommended" },
        { n: "Cultural Club", i: "Shows cultural competency for equitable healthcare.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and fine motor skills.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize and maintain focus.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and breath control.", t: "recommended" },
        { n: "Drama Club", i: "Enhances bedside manner and patient communication.", t: "recommended" },
        { n: "Art Club", i: "Develops fine motor skills useful in surgical contexts.", t: "recommended" },
        { n: "Photography", i: "Aids in visual observation and detail orientation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in clinical documentation.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on public health topics.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical stamina and coordination.", t: "recommended" },
        { n: "Varsity Soccer", i: "Demonstrates physical stamina needed for clinical work.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual perseverance through exhaustion.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and quick reaction times.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and continuous service.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible community care and physical effort.", t: "recommended" },
        { n: "Philosophy Club", i: "Fosters deep understanding of medical ethics.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of social determinants of health.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and basic biological care.", t: "recommended" },
        { n: "Baking Club", i: "Demonstrates precision in measurements and chemistry.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and record keeping.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future healthcare administration.", t: "recommended" },
        { n: "Debate Team", i: "Essential for advocating for patient care protocols.", t: "recommended" },
        { n: "Model UN", i: "Fosters awareness of global health initiatives (WHO).", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and empathy.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting work ethic and time management.", t: "recommended" },
        { n: "Film Club", i: "Aids in visual storytelling for health education.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and pediatric communication skills.", t: "recommended" },
        { n: "Lawn Care", i: "Shows independent hustle and physical endurance.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of environmental health impacts.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to explain diagnoses to patients clearly.", t: "recommended" }
    ]),
    "Engineering": hydrate([
        { n: "FIRST Robotics", i: "Proves multidisciplinary engineering and teamwork.", t: "essential" },
        { n: "Science Olympiad", i: "Validates elite theoretical and applied science skills.", t: "essential" },
        { n: "Makerspace", i: "Shows intrinsic drive for mechanical/electrical design.", t: "essential" },
        { n: "CAD Design", i: "Proves proficiency in industry-standard spatial tools.", t: "recommended" },
        { n: "Eng Intern", i: "Exposes student to professional engineering workflows.", t: "recommended" },
        { n: "Physics Bowl", i: "Validates the structural and kinetic math required.", t: "recommended" },
        { n: "Bridge Comp", i: "Demonstrates applied civil engineering and statics.", t: "recommended" },
        { n: "Rocketry", i: "Applies fluid dynamics and aerospace principles.", t: "recommended" },
        { n: "Auto Shop", i: "Shows gritty, hands-on mechanical troubleshooting.", t: "recommended" },
        { n: "Tinkering", i: "Highlights self-driven, iterative prototyping skills.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for calculus/differential.", t: "recommended" },
        { n: "Baking Club", i: "Shows precision in procedural steps and measurements.", t: "recommended" },
        { n: "Scouts", i: "Proves structural building and outdoor survival skills.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall and diverse knowledge.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and spatial logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and orbital mechanics.", t: "recommended" },
        { n: "History Club", i: "Provides context for the history of industrialization.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for global engineering projects and teams.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse corporate environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and complex math.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large structure.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and acoustic awareness.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and project presentation skills", t: "recommended" },
        { n: "Art Club", i: "Develops creative drafting and aesthetic design.", t: "recommended" },
        { n: "Photography", i: "Aids in visual documentation of structural prototypes.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management and layout.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in technical documentation.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on technological events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and spatial awareness", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and system-based teamwork.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual perseverance and measurable progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and geometric focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible civil construction and physical effort.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and logistical optimization skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in complex facilities.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and archiving systems.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future project management.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending structural proposals and bids.", t: "recommended" },
        { n: "Model UN", i: "Fosters awareness of global infrastructure challenges.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and communication.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting design generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and responsibility.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and interpersonal trust.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable engineering.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to explain technical concepts simply.", t: "recommended" }
    ]),
    "Arts / Design": hydrate([
        { n: "Portfolio Dev", i: "Serves as the primary metric of aesthetic capability.", t: "essential" },
        { n: "Scholastic Art", i: "Provides standardized, national-level talent validation.", t: "essential" },
        { n: "Muralist", i: "Takes aesthetic skills into the public, civic sphere.", t: "essential" },
        { n: "Freelance Design", i: "Shows entrepreneurial application of graphic design.", t: "recommended" },
        { n: "Art Honor Soc", i: "Validates formal dedication and peer leadership in art.", t: "recommended" },
        { n: "Set Design", i: "Applies spatial design and collaborative construction.", t: "recommended" },
        { n: "Gallery Intern", i: "Shows understanding of curation and professional art.", t: "recommended" },
        { n: "Animation Club", i: "Demonstrates digital mastery and sequential narrative.", t: "recommended" },
        { n: "3D Modeling", i: "Applies structural logic to digital aesthetics.", t: "recommended" },
        { n: "Art Club", i: "Fosters peer critique and diverse medium exploration.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor useful for geometric design.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and material science knowledge", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model light, shadow, and structure.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad cultural knowledge base useful for art context", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and visual planning.", t: "recommended" },
        { n: "Astronomy Club", i: "Inspires aesthetic appreciation for scale and space.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for art history movements.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for understanding global art traditions.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability to design for diverse audiences.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and auditory art.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large ensemble.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and group harmony.", t: "recommended" },
        { n: "Drama Club", i: "Enhances performative and visual storytelling skills.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and outdoor observation.", t: "recommended" },
        { n: "Photography", i: "Foundational for framing, lighting, and visual narrative.", t: "recommended" },
        { n: "Yearbook", i: "Provides applied layout, typography, and editing experience", t: "recommended" },
        { n: "Lit Mag", i: "Fuses visual illustration with creative writing.", t: "recommended" },
        { n: "School Paper", i: "Hones objective communication and editorial illustration.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates physical expression and kinetic art.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational teamwork.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and physical dedication.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and spatial design.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and visual organization skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and visual observation.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to bring art therapy to patients.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and respect for archives.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future creative direction.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending artistic choices and critique.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and cultural awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and sales skills.", t: "recommended" },
        { n: "Baking Club", i: "Applies aesthetic decoration and chemical precision.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and creative play.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and landscaping.", t: "recommended" },
        { n: "Enviro Club", i: "Inspires eco-friendly and sustainable design materials.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to critique and guide peer portfolios.", t: "recommended" }
    ]),
    "Biology": hydrate([
        { n: "Bio Olympiad", i: "Shows elite, specialized mastery of biological systems.", t: "essential" },
        { n: "Lab Research", i: "Proves mastery of the scientific method and lab work.", t: "essential" },
        { n: "Animal Rescue", i: "Demonstrates ethical stewardship and biological care.", t: "essential" },
        { n: "Science Olympiad", i: "Validates broad, competitive scientific knowledge.", t: "recommended" },
        { n: "Envirothon", i: "Applies biological concepts to macro-ecological systems.", t: "recommended" },
        { n: "Zoo Vol", i: "Shows long-term commitment to zoology and conservation.", t: "recommended" },
        { n: "Bio Club", i: "Fosters peer academic engagement and scientific curiosity", t: "recommended" },
        { n: "Stem Cell Camp", i: "Proves readiness for cutting-edge cellular biology.", t: "recommended" },
        { n: "Nature Center", i: "Educates the public on local botany and ecosystems.", t: "recommended" },
        { n: "Ecology Rsch", i: "Shows ability to synthesize field data and demographics.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for biostatistics.", t: "recommended" },
        { n: "Scouts", i: "Proves outdoor survival skills and environmental observation", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model biophysical energy systems.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall for complex taxonomy.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and diagnostic logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for the origins of carbon-based life.", t: "recommended" },
        { n: "History Club", i: "Provides context for the history of scientific discovery.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for reading global research publications.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse laboratory environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and focus.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large system.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and breath mechanics.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking for scientific presentations.", t: "recommended" },
        { n: "Art Club", i: "Develops fine motor skills useful in dissection/lab work", t: "recommended" },
        { n: "Photography", i: "Aids in microscopic and macroscopic visual documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in writing scientific abstracts.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local scientific events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and kinesiology.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and physiological endurance.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and biomechanical effort.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and quick reaction times.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and physical effort.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and physiological care.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of nutrition and public health.", t: "recommended" },
        { n: "Baking Club", i: "Demonstrates precision in measurements and biochemistry.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in clinical bio-environments", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity for research literature.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future lab management roles.", t: "recommended" },
        { n: "Debate Team", i: "Essential for defending scientific hypotheses and grants.", t: "recommended" },
        { n: "Model UN", i: "Fosters awareness of global bio-security and health.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and communication.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting data analysis and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and biological empathy.", t: "recommended" },
        { n: "Babysitting", i: "Builds patience and understanding of developmental biology", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and plant biology.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable bio-diversity.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to explain complex biology to peers.", t: "recommended" }
    ]),
    "Mathematics": hydrate([
        { n: "AMC / AIME", i: "Serves as the elite universal benchmark for math skills.", t: "essential" },
        { n: "Math Team", i: "Fosters collaborative problem-solving under pressure.", t: "essential" },
        { n: "Peer Tutor", i: "Proves ability to communicate abstract logical concepts.", t: "essential" },
        { n: "Data Science", i: "Applies statistical theory to real-world datasets.", t: "recommended" },
        { n: "Philosophy Club", i: "Develops rigorous formal logic and abstract reasoning.", t: "recommended" },
        { n: "Physics Bowl", i: "Shows the application of calculus in physical systems.", t: "recommended" },
        { n: "Crypto Club", i: "Applies number theory and modular arithmetic to security.", t: "recommended" },
        { n: "Math Camp", i: "Proves willingness to engage in intense, abstract study.", t: "recommended" },
        { n: "Stats Project", i: "Demonstrates mastery of probability and variance.", t: "recommended" },
        { n: "Algorithms", i: "Translates pure math into functional computer logic.", t: "recommended" },
        { n: "Baking Club", i: "Shows precision in procedural steps and fractional math.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and collaborative logic.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting variables.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows rapid information recall and diverse knowledge.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates deep strategic and spatial logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and complex datasets.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for the history of mathematics.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Aids in the cognitive flexibility of learning syntax.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse corporate/academic teams.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and rhythmic math.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large structure.", t: "recommended" },
        { n: "Choir", i: "Builds confident communication and harmonic ratios.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and academic presentation skills", t: "recommended" },
        { n: "Art Club", i: "Develops creative geometric and spatial aesthetics.", t: "recommended" },
        { n: "Photography", i: "Aids in understanding optics and geometric framing.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management and geometry.", t: "recommended" },
        { n: "Lit Mag", i: "Improves precision in writing mathematical proofs.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on academic/STEM events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and spatial patterns", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured kinematics.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and geometric trajectory focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and geometric application", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and resource allocation.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and statistical inventory skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in high-stress sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and categorization systems.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future academic departments.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and economic math awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and basic accounting.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting coding generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and area math.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of statistical climate modeling.", t: "recommended" },
        { n: "Peer Tutor (Gen)", i: "Proves ability to manage and instruct younger peers.", t: "recommended" }
    ]),
    "Political Science": hydrate([
        { n: "Model UN", i: "Hones geopolitical research and diplomatic negotiation.", t: "essential" },
        { n: "Debate Team", i: "Builds elite persuasive communication and logic skills.", t: "essential" },
        { n: "Campaign Vol", i: "Shows practical understanding of grassroots mobilization.", t: "essential" },
        { n: "Philosophy Club", i: "Develops rigorous ethical and political frameworks.", t: "recommended" },
        { n: "Mock Trial", i: "Develops rigorous legal reasoning and public speaking.", t: "recommended" },
        { n: "Pol Journalism", i: "Demonstrates deep policy analysis and civic awareness.", t: "recommended" },
        { n: "Youth Advisory", i: "Applies civic interests directly to local governance.", t: "recommended" },
        { n: "ACLU Chapter", i: "Shows commitment to civil rights and policy outcomes.", t: "recommended" },
        { n: "Policy Rsch", i: "Validates deep academic inquiry into legislative effects.", t: "recommended" },
        { n: "Canvassing", i: "Builds ground-level communication and voter engagement.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for polling statistics.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis for evidence-based policy.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting systems.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and civic reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad historical and political knowledge base.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and geopolitical logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and scientific funding policy", t: "recommended" },
        { n: "History Club", i: "Provides vital context for historical political cycles.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating international diplomacy.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for inclusive civic environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and civic ceremony.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection for public address.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and charismatic presentation.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding for political campaigns.", t: "recommended" },
        { n: "Photography", i: "Aids in photojournalism and political documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and speechwriting.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local political events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and routine.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational leadership.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and measured progress.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and housing policy.", t: "recommended" },
        { n: "Red Cross", i: "Highlights crisis management and disaster policy.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of social safety net logistics.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and administrative support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in public healthcare.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and community education.", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and informal networking.", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and rank progression.", t: "recommended" },
        { n: "Film Club", i: "Fosters political documentary making and media savvy.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and public relation.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of sustainable climate policy.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Psychology": hydrate([
        { n: "Crisis Hotline", i: "Proves immense emotional maturity and active listening.", t: "essential" },
        { n: "Psych Research", i: "Validates readiness for methodological data analysis.", t: "essential" },
        { n: "Active Minds", i: "Shows proactive leadership in destigmatizing psychology.", t: "essential" },
        { n: "Psych Club", i: "Demonstrates organized academic interest in the field.", t: "recommended" },
        { n: "Peer Mediation", i: "Applies conflict resolution and clinical empathy locally.", t: "recommended" },
        { n: "Memory Study", i: "Highlights the statistical side of cognitive study.", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and informal therapy tactics.", t: "recommended" },
        { n: "Alzheimer's Vol", i: "Builds patience and understanding of cognitive decline.", t: "recommended" },
        { n: "Camp Counselor", i: "Proves group management and pediatric psychology exposure", t: "recommended" },
        { n: "Scouts", i: "Proves structured leadership and peer mentorship.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for psychostatistics.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and neurobiology basics.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex, shifting variables.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad knowledge base useful for social context.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and cognitive mapping.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and complex datasets.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for the history of psychology.", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for understanding cross-cultural psychology.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse clinical environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and cognitive focus.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and group harmony.", t: "recommended" },
        { n: "Drama Club", i: "Enhances empathy through role-play and character study.", t: "recommended" },
        { n: "Art Club", i: "Develops creative expressions useful for art therapy.", t: "recommended" },
        { n: "Photography", i: "Aids in observational skills and behavioral documentation", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional copywriting and expressive writing.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local mental health events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and somatic therapy", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and organizational group dynamics", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and psychological grit.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and teamwork.", t: "recommended" },
        { n: "Red Cross", i: "Highlights psychological first aid and crisis management.", t: "recommended" },
        { n: "Food Bank", i: "Builds understanding of social determinants of health.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and animal-assisted therapy.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in clinical sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and record keeping.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future administrative roles.", t: "recommended" },
        { n: "Debate Team", i: "Essential for logical argumentation and behavioral logic.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and social psychology.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and behavioral obs.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and interpersonal care.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and child psychology insight.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle.", t: "recommended" },
        { n: "Enviro Club", i: "Fosters understanding of eco-psychology and well-being.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ]),
    "Environmental Science": hydrate([
        { n: "Climate Policy Adv", i: "Fuses ecological science with actionable civic lobbying.", t: "essential" },
        { n: "Envirothon", i: "Validates deep understanding of ecological systems.", t: "essential" },
        { n: "Trail Cleanup Vol", i: "Shows willingness to do the physical work of ecology.", t: "essential" },
        { n: "Sustainability Club", i: "Leads local initiatives like school recycling programs.", t: "recommended" },
        { n: "Ecology Rsch", i: "Proves ability to conduct field and lab data analysis.", t: "recommended" },
        { n: "Community Garden", i: "Connects environmental action with local food security.", t: "recommended" },
        { n: "Solar Project", i: "Applies engineering concepts to sustainability goals.", t: "recommended" },
        { n: "Wildlife Rescue", i: "Demonstrates direct ethical care for local biomes.", t: "recommended" },
        { n: "Baking Club", i: "Fosters community building and sourcing local ingredients", t: "recommended" },
        { n: "Beach Cleanup", i: "Shows grassroots commitment to marine conservation.", t: "recommended" },
        { n: "Math Team", i: "Shows quantitative rigor needed for climate statistics.", t: "recommended" },
        { n: "Science Olympiad", i: "Builds data-driven analysis and environmental chem.", t: "recommended" },
        { n: "Physics Club", i: "Proves ability to model complex energy thermodynamics.", t: "recommended" },
        { n: "National Honor Soc", i: "Validates a high academic baseline and reliability.", t: "recommended" },
        { n: "Quiz Bowl", i: "Shows broad knowledge base useful for geo-context.", t: "recommended" },
        { n: "Chess Club", i: "Demonstrates strategic foresight and systemic logic.", t: "recommended" },
        { n: "Astronomy Club", i: "Shows appreciation for scale and planetary sciences.", t: "recommended" },
        { n: "History Club", i: "Provides vital context for industrial and climate history", t: "recommended" },
        { n: "Foreign Lang Club", i: "Essential for navigating global climate agreements.", t: "recommended" },
        { n: "Cultural Club", i: "Shows capability for diverse corporate environments.", t: "recommended" },
        { n: "Band", i: "Fosters organizational discipline and coordination.", t: "recommended" },
        { n: "Orchestra", i: "Proves ability to synchronize within a large team.", t: "recommended" },
        { n: "Choir", i: "Builds confident vocal projection and group harmony.", t: "recommended" },
        { n: "Drama Club", i: "Enhances public speaking and policy pitch skills.", t: "recommended" },
        { n: "Art Club", i: "Develops creative branding for environmental campaigns.", t: "recommended" },
        { n: "Photography", i: "Aids in photojournalism and conservation documentation.", t: "recommended" },
        { n: "Yearbook", i: "Provides collaborative project management experience.", t: "recommended" },
        { n: "Lit Mag", i: "Improves professional nature writing and editing.", t: "recommended" },
        { n: "School Paper", i: "Hones objective reporting on local ecological events.", t: "recommended" },
        { n: "Dance Team", i: "Demonstrates high physical discipline and routine.", t: "recommended" },
        { n: "Varsity Soccer", i: "Proves competitive drive and outdoor stamina.", t: "recommended" },
        { n: "Track & Field", i: "Shows individual goal-setting and physical endurance.", t: "recommended" },
        { n: "Tennis", i: "Proves strategic agility and independent focus.", t: "recommended" },
        { n: "Key Club", i: "Demonstrates civic networking and service logistics.", t: "recommended" },
        { n: "Habitat for Humanity", i: "Shows tangible project completion and green building.", t: "recommended" },
        { n: "Red Cross", i: "Highlights natural disaster crisis management.", t: "recommended" },
        { n: "Food Bank", i: "Builds supply chain and agricultural network skills.", t: "recommended" },
        { n: "Animal Rescue", i: "Shows consistent empathy and zoological support.", t: "recommended" },
        { n: "Hospital Vol", i: "Highlights ability to operate in health sectors.", t: "recommended" },
        { n: "Library Vol", i: "Shows organizational capacity and research archiving.", t: "recommended" },
        { n: "Student Gov", i: "Builds leadership for future environmental policy.", t: "recommended" },
        { n: "Debate Team", i: "Essential for contract negotiation and policy debate.", t: "recommended" },
        { n: "Model UN", i: "Fosters macro-geopolitical and climate treaty awareness.", t: "recommended" },
        { n: "Retail Job", i: "Builds foundational customer service and sales skills.", t: "recommended" },
        { n: "Freelance", i: "Proves self-starting business generation and billing.", t: "recommended" },
        { n: "Family Care", i: "Shows immense time management and maturity.", t: "recommended" },
        { n: "Babysitting", i: "Builds interpersonal trust and localized networking.", t: "recommended" },
        { n: "Lawn Care", i: "Shows grassroots entrepreneurial hustle and botany.", t: "recommended" },
        { n: "Scouts", i: "Proves structured outdoor leadership and conservation.", t: "recommended" },
        { n: "Peer Tutor", i: "Proves ability to manage and instruct personnel.", t: "recommended" }
    ])
};
