export type LandingIconName =
  | "shield"
  | "calendar"
  | "penTool"
  | "target"
  | "bookOpen"
  | "barChart3"
  | "sparkles"
  | "layers"
  | "clock"
  | "messageSquare"
  | "users"
  | "graduationCap";

export interface NavItem {
  label: string;
  href: string;
}

export interface HeroMetric {
  label: string;
  value: string;
  caption: string;
}

export interface FeatureItem {
  icon: LandingIconName;
  title: string;
  description: string;
  eyebrow: string;
  highlight: string;
}

export interface ProcessStep {
  id: string;
  title: string;
  description: string;
  detail: string;
}

export interface DashboardStat {
  label: string;
  value: string;
  trend: string;
  icon: LandingIconName;
}

export interface DashboardDeadline {
  title: string;
  date: string;
  urgency: "high" | "medium" | "low";
}

export interface BalanceBand {
  label: string;
  percent: number;
  color: string;
}

export interface FaqItem {
  question: string;
  answer: string;
}

export const NAV_ITEMS: readonly NavItem[] = [
  { label: "Platform", href: "#platform" },
  { label: "Features", href: "#features" },
  { label: "Process", href: "#process" },
  { label: "FAQ", href: "#faq" },
] as const;

export const HERO_LABEL = "YOUR STRATEGIC APPLICATION PLATFORM";

export const HERO_TITLE_TOP = "Navigate your path to the";
export const HERO_TITLE_EMPHASIS = "world's best universities";

export const HERO_DESCRIPTION =
  "UNIMAP gives international students a structured, invite-only platform to plan, track, and execute every step of the university application process.";

export const HERO_CHIPS: readonly string[] = [
  "Invite-only",
  "Timeline intelligence",
  "Essay workspace",
  "College strategy",
  "Teacher oversight",
  "Performance analytics",
] as const;

export const HERO_METRICS: readonly HeroMetric[] = [
  {
    label: "students",
    value: "2.4K+",
    caption: "active applicants planning weekly",
  },
  {
    label: "deadlines",
    value: "96%",
    caption: "submitted on time with timeline support",
  },
  {
    label: "essays",
    value: "14K+",
    caption: "draft iterations tracked across cohorts",
  },
  {
    label: "acceptances",
    value: "71%",
    caption: "offers from top-choice universities",
  },
] as const;

export const FEATURE_ITEMS: readonly FeatureItem[] = [
  {
    icon: "shield",
    title: "Secure Access",
    description:
      "Invite-only onboarding and role-based permissions keep each cohort private, organized, and protected.",
    eyebrow: "Trust",
    highlight: "Role-based governance",
  },
  {
    icon: "calendar",
    title: "Timeline Tracking",
    description:
      "Visual planning with milestone groups, reminders, and deadline dependencies so nothing is missed.",
    eyebrow: "Planning",
    highlight: "Dependency-aware deadlines",
  },
  {
    icon: "penTool",
    title: "Essay Workspace",
    description:
      "Write, version, and refine your essays with history snapshots, strategic notes, and review context.",
    eyebrow: "Writing",
    highlight: "Draft version control",
  },
  {
    icon: "target",
    title: "College Matching",
    description:
      "Build a balanced list with reach/target/safety recommendations backed by profile-aware fit scoring.",
    eyebrow: "Strategy",
    highlight: "Profile-fit modeling",
  },
  {
    icon: "bookOpen",
    title: "Class Management",
    description:
      "Teachers coordinate assignments, attendance, and class updates while students follow one shared plan.",
    eyebrow: "Academics",
    highlight: "Classroom coordination",
  },
  {
    icon: "barChart3",
    title: "Smart Analytics",
    description:
      "Progress dashboards convert your activity into clear next actions for faster, higher-quality decisions.",
    eyebrow: "Insights",
    highlight: "Action-first reporting",
  },
] as const;

export const PROCESS_STEPS: readonly ProcessStep[] = [
  {
    id: "01",
    title: "Get Invited",
    description:
      "Receive your invite code and activate a profile tied to your cohort and counselor workflow.",
    detail: "Secure onboarding",
  },
  {
    id: "02",
    title: "Build Your Profile",
    description:
      "Capture academics, activities, testing, and constraints so recommendations match your goals.",
    detail: "Structured profile",
  },
  {
    id: "03",
    title: "Plan and Execute",
    description:
      "Turn strategy into milestones, drafts, and submission tasks with transparent ownership.",
    detail: "Execution rhythm",
  },
  {
    id: "04",
    title: "Apply with Confidence",
    description:
      "Submit polished applications with less stress, higher quality, and clear accountability.",
    detail: "Confident delivery",
  },
] as const;

export const DASHBOARD_STATS: readonly DashboardStat[] = [
  {
    label: "Deadlines",
    value: "12",
    trend: "+3 this week",
    icon: "calendar",
  },
  {
    label: "Essays",
    value: "8",
    trend: "5 in review",
    icon: "penTool",
  },
  {
    label: "Schools",
    value: "15",
    trend: "Balanced list",
    icon: "target",
  },
  {
    label: "Messages",
    value: "3",
    trend: "All unread",
    icon: "messageSquare",
  },
] as const;

export const DASHBOARD_DEADLINES: readonly DashboardDeadline[] = [
  {
    title: "MIT Early Action",
    date: "Nov 01",
    urgency: "high",
  },
  {
    title: "Stanford REA",
    date: "Nov 01",
    urgency: "high",
  },
  {
    title: "Columbia ED",
    date: "Nov 01",
    urgency: "medium",
  },
  {
    title: "UC Application",
    date: "Nov 30",
    urgency: "medium",
  },
  {
    title: "Scholarship Packet",
    date: "Dec 05",
    urgency: "low",
  },
] as const;

export const BALANCE_BANDS: readonly BalanceBand[] = [
  {
    label: "Reach",
    percent: 40,
    color: "#d63a43",
  },
  {
    label: "Target",
    percent: 36,
    color: "#f59e0b",
  },
  {
    label: "Safety",
    percent: 24,
    color: "#10b981",
  },
] as const;

export const FAQ_ITEMS: readonly FaqItem[] = [
  {
    question: "How do I get access to UNIMAP?",
    answer:
      "UNIMAP is invite-only. Students receive access through counselors, partner schools, or approved referral codes.",
  },
  {
    question: "Is this only for US applications?",
    answer:
      "No. UNIMAP supports planning for US, UK, Europe, and other international destinations with configurable workflows.",
  },
  {
    question: "Can counselors and teachers collaborate in real time?",
    answer:
      "Yes. Educators can manage classes, assignments, attendance, and application oversight while students work in shared timelines.",
  },
  {
    question: "How is student data protected?",
    answer:
      "Access control, secure infrastructure, and strict data boundaries ensure each student's materials are only visible to authorized roles.",
  },
  {
    question: "Does UNIMAP replace traditional counseling?",
    answer:
      "No. It strengthens counseling by making planning, communication, and execution measurable and transparent.",
  },
  {
    question: "Can I migrate from spreadsheets and docs?",
    answer:
      "Yes. Most teams start by importing milestones and essay inventories, then phase in class workflows and analytics.",
  },
  {
    question: "Do you support multi-cohort schools?",
    answer:
      "Yes. Cohort segmentation and role permissions allow departments to run parallel cycles without overlap.",
  },
  {
    question: "Is there a mobile experience?",
    answer:
      "The platform is responsive for planning and quick updates on mobile, with full workflow depth optimized for desktop.",
  },
] as const;

export const FOOTER_LINKS = [
  { label: "Privacy", href: "/privacy" },
  { label: "Terms", href: "/terms" },
  { label: "Security", href: "/security" },
  { label: "Contact", href: "mailto:contact@unimap.io" },
] as const;

export const UNIVERSITY_MARQUEE = [
  "Global Partner University 0001",
  "Global Partner University 0002",
  "Global Partner University 0003",
  "Global Partner University 0004",
  "Global Partner University 0005",
  "Global Partner University 0006",
  "Global Partner University 0007",
  "Global Partner University 0008",
  "Global Partner University 0009",
  "Global Partner University 0010",
  "Global Partner University 0011",
  "Global Partner University 0012",
  "Global Partner University 0013",
  "Global Partner University 0014",
  "Global Partner University 0015",
  "Global Partner University 0016",
  "Global Partner University 0017",
  "Global Partner University 0018",
  "Global Partner University 0019",
  "Global Partner University 0020",
  "Global Partner University 0021",
  "Global Partner University 0022",
  "Global Partner University 0023",
  "Global Partner University 0024",
  "Global Partner University 0025",
  "Global Partner University 0026",
  "Global Partner University 0027",
  "Global Partner University 0028",
  "Global Partner University 0029",
  "Global Partner University 0030",
  "Global Partner University 0031",
  "Global Partner University 0032",
  "Global Partner University 0033",
  "Global Partner University 0034",
  "Global Partner University 0035",
  "Global Partner University 0036",
  "Global Partner University 0037",
  "Global Partner University 0038",
  "Global Partner University 0039",
  "Global Partner University 0040",
  "Global Partner University 0041",
  "Global Partner University 0042",
  "Global Partner University 0043",
  "Global Partner University 0044",
  "Global Partner University 0045",
  "Global Partner University 0046",
  "Global Partner University 0047",
  "Global Partner University 0048",
  "Global Partner University 0049",
  "Global Partner University 0050",
  "Global Partner University 0051",
  "Global Partner University 0052",
  "Global Partner University 0053",
  "Global Partner University 0054",
  "Global Partner University 0055",
  "Global Partner University 0056",
  "Global Partner University 0057",
  "Global Partner University 0058",
  "Global Partner University 0059",
  "Global Partner University 0060",
  "Global Partner University 0061",
  "Global Partner University 0062",
  "Global Partner University 0063",
  "Global Partner University 0064",
  "Global Partner University 0065",
  "Global Partner University 0066",
  "Global Partner University 0067",
  "Global Partner University 0068",
  "Global Partner University 0069",
  "Global Partner University 0070",
  "Global Partner University 0071",
  "Global Partner University 0072",
  "Global Partner University 0073",
  "Global Partner University 0074",
  "Global Partner University 0075",
  "Global Partner University 0076",
  "Global Partner University 0077",
  "Global Partner University 0078",
  "Global Partner University 0079",
  "Global Partner University 0080",
  "Global Partner University 0081",
  "Global Partner University 0082",
  "Global Partner University 0083",
  "Global Partner University 0084",
  "Global Partner University 0085",
  "Global Partner University 0086",
  "Global Partner University 0087",
  "Global Partner University 0088",
  "Global Partner University 0089",
  "Global Partner University 0090",
  "Global Partner University 0091",
  "Global Partner University 0092",
  "Global Partner University 0093",
  "Global Partner University 0094",
  "Global Partner University 0095",
  "Global Partner University 0096",
  "Global Partner University 0097",
  "Global Partner University 0098",
  "Global Partner University 0099",
  "Global Partner University 0100",
  "Global Partner University 0101",
  "Global Partner University 0102",
  "Global Partner University 0103",
  "Global Partner University 0104",
  "Global Partner University 0105",
  "Global Partner University 0106",
  "Global Partner University 0107",
  "Global Partner University 0108",
  "Global Partner University 0109",
  "Global Partner University 0110",
  "Global Partner University 0111",
  "Global Partner University 0112",
  "Global Partner University 0113",
  "Global Partner University 0114",
  "Global Partner University 0115",
  "Global Partner University 0116",
  "Global Partner University 0117",
  "Global Partner University 0118",
  "Global Partner University 0119",
  "Global Partner University 0120",
  "Global Partner University 0121",
  "Global Partner University 0122",
  "Global Partner University 0123",
  "Global Partner University 0124",
  "Global Partner University 0125",
  "Global Partner University 0126",
  "Global Partner University 0127",
  "Global Partner University 0128",
  "Global Partner University 0129",
  "Global Partner University 0130",
  "Global Partner University 0131",
  "Global Partner University 0132",
  "Global Partner University 0133",
  "Global Partner University 0134",
  "Global Partner University 0135",
  "Global Partner University 0136",
  "Global Partner University 0137",
  "Global Partner University 0138",
  "Global Partner University 0139",
  "Global Partner University 0140",
  "Global Partner University 0141",
  "Global Partner University 0142",
  "Global Partner University 0143",
  "Global Partner University 0144",
  "Global Partner University 0145",
  "Global Partner University 0146",
  "Global Partner University 0147",
  "Global Partner University 0148",
  "Global Partner University 0149",
  "Global Partner University 0150",
  "Global Partner University 0151",
  "Global Partner University 0152",
  "Global Partner University 0153",
  "Global Partner University 0154",
  "Global Partner University 0155",
  "Global Partner University 0156",
  "Global Partner University 0157",
  "Global Partner University 0158",
  "Global Partner University 0159",
  "Global Partner University 0160",
  "Global Partner University 0161",
  "Global Partner University 0162",
  "Global Partner University 0163",
  "Global Partner University 0164",
  "Global Partner University 0165",
  "Global Partner University 0166",
  "Global Partner University 0167",
  "Global Partner University 0168",
  "Global Partner University 0169",
  "Global Partner University 0170",
  "Global Partner University 0171",
  "Global Partner University 0172",
  "Global Partner University 0173",
  "Global Partner University 0174",
  "Global Partner University 0175",
  "Global Partner University 0176",
  "Global Partner University 0177",
  "Global Partner University 0178",
  "Global Partner University 0179",
  "Global Partner University 0180",
  "Global Partner University 0181",
  "Global Partner University 0182",
  "Global Partner University 0183",
  "Global Partner University 0184",
  "Global Partner University 0185",
  "Global Partner University 0186",
  "Global Partner University 0187",
  "Global Partner University 0188",
  "Global Partner University 0189",
  "Global Partner University 0190",
  "Global Partner University 0191",
  "Global Partner University 0192",
  "Global Partner University 0193",
  "Global Partner University 0194",
  "Global Partner University 0195",
  "Global Partner University 0196",
  "Global Partner University 0197",
  "Global Partner University 0198",
  "Global Partner University 0199",
  "Global Partner University 0200",
  "Global Partner University 0201",
  "Global Partner University 0202",
  "Global Partner University 0203",
  "Global Partner University 0204",
  "Global Partner University 0205",
  "Global Partner University 0206",
  "Global Partner University 0207",
  "Global Partner University 0208",
  "Global Partner University 0209",
  "Global Partner University 0210",
  "Global Partner University 0211",
  "Global Partner University 0212",
  "Global Partner University 0213",
  "Global Partner University 0214",
  "Global Partner University 0215",
  "Global Partner University 0216",
  "Global Partner University 0217",
  "Global Partner University 0218",
  "Global Partner University 0219",
  "Global Partner University 0220",
  "Global Partner University 0221",
  "Global Partner University 0222",
  "Global Partner University 0223",
  "Global Partner University 0224",
  "Global Partner University 0225",
  "Global Partner University 0226",
  "Global Partner University 0227",
  "Global Partner University 0228",
  "Global Partner University 0229",
  "Global Partner University 0230",
  "Global Partner University 0231",
  "Global Partner University 0232",
  "Global Partner University 0233",
  "Global Partner University 0234",
  "Global Partner University 0235",
  "Global Partner University 0236",
  "Global Partner University 0237",
  "Global Partner University 0238",
  "Global Partner University 0239",
  "Global Partner University 0240",
  "Global Partner University 0241",
  "Global Partner University 0242",
  "Global Partner University 0243",
  "Global Partner University 0244",
  "Global Partner University 0245",
  "Global Partner University 0246",
  "Global Partner University 0247",
  "Global Partner University 0248",
  "Global Partner University 0249",
  "Global Partner University 0250",
  "Global Partner University 0251",
  "Global Partner University 0252",
  "Global Partner University 0253",
  "Global Partner University 0254",
  "Global Partner University 0255",
  "Global Partner University 0256",
  "Global Partner University 0257",
  "Global Partner University 0258",
  "Global Partner University 0259",
  "Global Partner University 0260",
  "Global Partner University 0261",
  "Global Partner University 0262",
  "Global Partner University 0263",
  "Global Partner University 0264",
  "Global Partner University 0265",
  "Global Partner University 0266",
  "Global Partner University 0267",
  "Global Partner University 0268",
  "Global Partner University 0269",
  "Global Partner University 0270",
  "Global Partner University 0271",
  "Global Partner University 0272",
  "Global Partner University 0273",
  "Global Partner University 0274",
  "Global Partner University 0275",
  "Global Partner University 0276",
  "Global Partner University 0277",
  "Global Partner University 0278",
  "Global Partner University 0279",
  "Global Partner University 0280",
  "Global Partner University 0281",
  "Global Partner University 0282",
  "Global Partner University 0283",
  "Global Partner University 0284",
  "Global Partner University 0285",
  "Global Partner University 0286",
  "Global Partner University 0287",
  "Global Partner University 0288",
  "Global Partner University 0289",
  "Global Partner University 0290",
  "Global Partner University 0291",
  "Global Partner University 0292",
  "Global Partner University 0293",
  "Global Partner University 0294",
  "Global Partner University 0295",
  "Global Partner University 0296",
  "Global Partner University 0297",
  "Global Partner University 0298",
  "Global Partner University 0299",
  "Global Partner University 0300",
  "Global Partner University 0301",
  "Global Partner University 0302",
  "Global Partner University 0303",
  "Global Partner University 0304",
  "Global Partner University 0305",
  "Global Partner University 0306",
  "Global Partner University 0307",
  "Global Partner University 0308",
  "Global Partner University 0309",
  "Global Partner University 0310",
  "Global Partner University 0311",
  "Global Partner University 0312",
  "Global Partner University 0313",
  "Global Partner University 0314",
  "Global Partner University 0315",
  "Global Partner University 0316",
  "Global Partner University 0317",
  "Global Partner University 0318",
  "Global Partner University 0319",
  "Global Partner University 0320",
  "Global Partner University 0321",
  "Global Partner University 0322",
  "Global Partner University 0323",
  "Global Partner University 0324",
  "Global Partner University 0325",
  "Global Partner University 0326",
  "Global Partner University 0327",
  "Global Partner University 0328",
  "Global Partner University 0329",
  "Global Partner University 0330",
  "Global Partner University 0331",
  "Global Partner University 0332",
  "Global Partner University 0333",
  "Global Partner University 0334",
  "Global Partner University 0335",
  "Global Partner University 0336",
  "Global Partner University 0337",
  "Global Partner University 0338",
  "Global Partner University 0339",
  "Global Partner University 0340",
  "Global Partner University 0341",
  "Global Partner University 0342",
  "Global Partner University 0343",
  "Global Partner University 0344",
  "Global Partner University 0345",
  "Global Partner University 0346",
  "Global Partner University 0347",
  "Global Partner University 0348",
  "Global Partner University 0349",
  "Global Partner University 0350",
  "Global Partner University 0351",
  "Global Partner University 0352",
  "Global Partner University 0353",
  "Global Partner University 0354",
  "Global Partner University 0355",
  "Global Partner University 0356",
  "Global Partner University 0357",
  "Global Partner University 0358",
  "Global Partner University 0359",
  "Global Partner University 0360",
  "Global Partner University 0361",
  "Global Partner University 0362",
  "Global Partner University 0363",
  "Global Partner University 0364",
  "Global Partner University 0365",
  "Global Partner University 0366",
  "Global Partner University 0367",
  "Global Partner University 0368",
  "Global Partner University 0369",
  "Global Partner University 0370",
  "Global Partner University 0371",
  "Global Partner University 0372",
  "Global Partner University 0373",
  "Global Partner University 0374",
  "Global Partner University 0375",
  "Global Partner University 0376",
  "Global Partner University 0377",
  "Global Partner University 0378",
  "Global Partner University 0379",
  "Global Partner University 0380",
  "Global Partner University 0381",
  "Global Partner University 0382",
  "Global Partner University 0383",
  "Global Partner University 0384",
  "Global Partner University 0385",
  "Global Partner University 0386",
  "Global Partner University 0387",
  "Global Partner University 0388",
  "Global Partner University 0389",
  "Global Partner University 0390",
  "Global Partner University 0391",
  "Global Partner University 0392",
  "Global Partner University 0393",
  "Global Partner University 0394",
  "Global Partner University 0395",
  "Global Partner University 0396",
  "Global Partner University 0397",
  "Global Partner University 0398",
  "Global Partner University 0399",
  "Global Partner University 0400",
  "Global Partner University 0401",
  "Global Partner University 0402",
  "Global Partner University 0403",
  "Global Partner University 0404",
  "Global Partner University 0405",
  "Global Partner University 0406",
  "Global Partner University 0407",
  "Global Partner University 0408",
  "Global Partner University 0409",
  "Global Partner University 0410",
  "Global Partner University 0411",
  "Global Partner University 0412",
  "Global Partner University 0413",
  "Global Partner University 0414",
  "Global Partner University 0415",
  "Global Partner University 0416",
  "Global Partner University 0417",
  "Global Partner University 0418",
  "Global Partner University 0419",
  "Global Partner University 0420",
  "Global Partner University 0421",
  "Global Partner University 0422",
  "Global Partner University 0423",
  "Global Partner University 0424",
  "Global Partner University 0425",
  "Global Partner University 0426",
  "Global Partner University 0427",
  "Global Partner University 0428",
  "Global Partner University 0429",
  "Global Partner University 0430",
  "Global Partner University 0431",
  "Global Partner University 0432",
  "Global Partner University 0433",
  "Global Partner University 0434",
  "Global Partner University 0435",
  "Global Partner University 0436",
  "Global Partner University 0437",
  "Global Partner University 0438",
  "Global Partner University 0439",
  "Global Partner University 0440",
  "Global Partner University 0441",
  "Global Partner University 0442",
  "Global Partner University 0443",
  "Global Partner University 0444",
  "Global Partner University 0445",
  "Global Partner University 0446",
  "Global Partner University 0447",
  "Global Partner University 0448",
  "Global Partner University 0449",
  "Global Partner University 0450",
  "Global Partner University 0451",
  "Global Partner University 0452",
  "Global Partner University 0453",
  "Global Partner University 0454",
  "Global Partner University 0455",
  "Global Partner University 0456",
  "Global Partner University 0457",
  "Global Partner University 0458",
  "Global Partner University 0459",
  "Global Partner University 0460",
  "Global Partner University 0461",
  "Global Partner University 0462",
  "Global Partner University 0463",
  "Global Partner University 0464",
  "Global Partner University 0465",
  "Global Partner University 0466",
  "Global Partner University 0467",
  "Global Partner University 0468",
  "Global Partner University 0469",
  "Global Partner University 0470",
  "Global Partner University 0471",
  "Global Partner University 0472",
  "Global Partner University 0473",
  "Global Partner University 0474",
  "Global Partner University 0475",
  "Global Partner University 0476",
  "Global Partner University 0477",
  "Global Partner University 0478",
  "Global Partner University 0479",
  "Global Partner University 0480",
  "Global Partner University 0481",
  "Global Partner University 0482",
  "Global Partner University 0483",
  "Global Partner University 0484",
  "Global Partner University 0485",
  "Global Partner University 0486",
  "Global Partner University 0487",
  "Global Partner University 0488",
  "Global Partner University 0489",
  "Global Partner University 0490",
  "Global Partner University 0491",
  "Global Partner University 0492",
  "Global Partner University 0493",
  "Global Partner University 0494",
  "Global Partner University 0495",
  "Global Partner University 0496",
  "Global Partner University 0497",
  "Global Partner University 0498",
  "Global Partner University 0499",
  "Global Partner University 0500",
  "Global Partner University 0501",
  "Global Partner University 0502",
  "Global Partner University 0503",
  "Global Partner University 0504",
  "Global Partner University 0505",
  "Global Partner University 0506",
  "Global Partner University 0507",
  "Global Partner University 0508",
  "Global Partner University 0509",
  "Global Partner University 0510",
  "Global Partner University 0511",
  "Global Partner University 0512",
  "Global Partner University 0513",
  "Global Partner University 0514",
  "Global Partner University 0515",
  "Global Partner University 0516",
  "Global Partner University 0517",
  "Global Partner University 0518",
  "Global Partner University 0519",
  "Global Partner University 0520",
  "Global Partner University 0521",
  "Global Partner University 0522",
  "Global Partner University 0523",
  "Global Partner University 0524",
  "Global Partner University 0525",
  "Global Partner University 0526",
  "Global Partner University 0527",
  "Global Partner University 0528",
  "Global Partner University 0529",
  "Global Partner University 0530",
  "Global Partner University 0531",
  "Global Partner University 0532",
  "Global Partner University 0533",
  "Global Partner University 0534",
  "Global Partner University 0535",
  "Global Partner University 0536",
  "Global Partner University 0537",
  "Global Partner University 0538",
  "Global Partner University 0539",
  "Global Partner University 0540",
  "Global Partner University 0541",
  "Global Partner University 0542",
  "Global Partner University 0543",
  "Global Partner University 0544",
  "Global Partner University 0545",
  "Global Partner University 0546",
  "Global Partner University 0547",
  "Global Partner University 0548",
  "Global Partner University 0549",
  "Global Partner University 0550",
  "Global Partner University 0551",
  "Global Partner University 0552",
  "Global Partner University 0553",
  "Global Partner University 0554",
  "Global Partner University 0555",
  "Global Partner University 0556",
  "Global Partner University 0557",
  "Global Partner University 0558",
  "Global Partner University 0559",
  "Global Partner University 0560",
  "Global Partner University 0561",
  "Global Partner University 0562",
  "Global Partner University 0563",
  "Global Partner University 0564",
  "Global Partner University 0565",
  "Global Partner University 0566",
  "Global Partner University 0567",
  "Global Partner University 0568",
  "Global Partner University 0569",
  "Global Partner University 0570",
  "Global Partner University 0571",
  "Global Partner University 0572",
  "Global Partner University 0573",
  "Global Partner University 0574",
  "Global Partner University 0575",
  "Global Partner University 0576",
  "Global Partner University 0577",
  "Global Partner University 0578",
  "Global Partner University 0579",
  "Global Partner University 0580",
  "Global Partner University 0581",
  "Global Partner University 0582",
  "Global Partner University 0583",
  "Global Partner University 0584",
  "Global Partner University 0585",
  "Global Partner University 0586",
  "Global Partner University 0587",
  "Global Partner University 0588",
  "Global Partner University 0589",
  "Global Partner University 0590",
  "Global Partner University 0591",
  "Global Partner University 0592",
  "Global Partner University 0593",
  "Global Partner University 0594",
  "Global Partner University 0595",
  "Global Partner University 0596",
  "Global Partner University 0597",
  "Global Partner University 0598",
  "Global Partner University 0599",
  "Global Partner University 0600",
  "Global Partner University 0601",
  "Global Partner University 0602",
  "Global Partner University 0603",
  "Global Partner University 0604",
  "Global Partner University 0605",
  "Global Partner University 0606",
  "Global Partner University 0607",
  "Global Partner University 0608",
  "Global Partner University 0609",
  "Global Partner University 0610",
  "Global Partner University 0611",
  "Global Partner University 0612",
  "Global Partner University 0613",
  "Global Partner University 0614",
  "Global Partner University 0615",
  "Global Partner University 0616",
  "Global Partner University 0617",
  "Global Partner University 0618",
  "Global Partner University 0619",
  "Global Partner University 0620",
  "Global Partner University 0621",
  "Global Partner University 0622",
  "Global Partner University 0623",
  "Global Partner University 0624",
  "Global Partner University 0625",
  "Global Partner University 0626",
  "Global Partner University 0627",
  "Global Partner University 0628",
  "Global Partner University 0629",
  "Global Partner University 0630",
  "Global Partner University 0631",
  "Global Partner University 0632",
  "Global Partner University 0633",
  "Global Partner University 0634",
  "Global Partner University 0635",
  "Global Partner University 0636",
  "Global Partner University 0637",
  "Global Partner University 0638",
  "Global Partner University 0639",
  "Global Partner University 0640",
  "Global Partner University 0641",
  "Global Partner University 0642",
  "Global Partner University 0643",
  "Global Partner University 0644",
  "Global Partner University 0645",
  "Global Partner University 0646",
  "Global Partner University 0647",
  "Global Partner University 0648",
  "Global Partner University 0649",
  "Global Partner University 0650",
  "Global Partner University 0651",
  "Global Partner University 0652",
  "Global Partner University 0653",
  "Global Partner University 0654",
  "Global Partner University 0655",
  "Global Partner University 0656",
  "Global Partner University 0657",
  "Global Partner University 0658",
  "Global Partner University 0659",
  "Global Partner University 0660",
  "Global Partner University 0661",
  "Global Partner University 0662",
  "Global Partner University 0663",
  "Global Partner University 0664",
  "Global Partner University 0665",
  "Global Partner University 0666",
  "Global Partner University 0667",
  "Global Partner University 0668",
  "Global Partner University 0669",
  "Global Partner University 0670",
  "Global Partner University 0671",
  "Global Partner University 0672",
  "Global Partner University 0673",
  "Global Partner University 0674",
  "Global Partner University 0675",
  "Global Partner University 0676",
  "Global Partner University 0677",
  "Global Partner University 0678",
  "Global Partner University 0679",
  "Global Partner University 0680",
  "Global Partner University 0681",
  "Global Partner University 0682",
  "Global Partner University 0683",
  "Global Partner University 0684",
  "Global Partner University 0685",
  "Global Partner University 0686",
  "Global Partner University 0687",
  "Global Partner University 0688",
  "Global Partner University 0689",
  "Global Partner University 0690",
  "Global Partner University 0691",
  "Global Partner University 0692",
  "Global Partner University 0693",
  "Global Partner University 0694",
  "Global Partner University 0695",
  "Global Partner University 0696",
  "Global Partner University 0697",
  "Global Partner University 0698",
  "Global Partner University 0699",
  "Global Partner University 0700",
  "Global Partner University 0701",
  "Global Partner University 0702",
  "Global Partner University 0703",
  "Global Partner University 0704",
  "Global Partner University 0705",
  "Global Partner University 0706",
  "Global Partner University 0707",
  "Global Partner University 0708",
  "Global Partner University 0709",
  "Global Partner University 0710",
  "Global Partner University 0711",
  "Global Partner University 0712",
  "Global Partner University 0713",
  "Global Partner University 0714",
  "Global Partner University 0715",
  "Global Partner University 0716",
  "Global Partner University 0717",
  "Global Partner University 0718",
  "Global Partner University 0719",
  "Global Partner University 0720",
  "Global Partner University 0721",
  "Global Partner University 0722",
  "Global Partner University 0723",
  "Global Partner University 0724",
  "Global Partner University 0725",
  "Global Partner University 0726",
  "Global Partner University 0727",
  "Global Partner University 0728",
  "Global Partner University 0729",
  "Global Partner University 0730",
  "Global Partner University 0731",
  "Global Partner University 0732",
  "Global Partner University 0733",
  "Global Partner University 0734",
  "Global Partner University 0735",
  "Global Partner University 0736",
  "Global Partner University 0737",
  "Global Partner University 0738",
  "Global Partner University 0739",
  "Global Partner University 0740",
  "Global Partner University 0741",
  "Global Partner University 0742",
  "Global Partner University 0743",
  "Global Partner University 0744",
  "Global Partner University 0745",
  "Global Partner University 0746",
  "Global Partner University 0747",
  "Global Partner University 0748",
  "Global Partner University 0749",
  "Global Partner University 0750",
  "Global Partner University 0751",
  "Global Partner University 0752",
  "Global Partner University 0753",
  "Global Partner University 0754",
  "Global Partner University 0755",
  "Global Partner University 0756",
  "Global Partner University 0757",
  "Global Partner University 0758",
  "Global Partner University 0759",
  "Global Partner University 0760",
  "Global Partner University 0761",
  "Global Partner University 0762",
  "Global Partner University 0763",
  "Global Partner University 0764",
  "Global Partner University 0765",
  "Global Partner University 0766",
  "Global Partner University 0767",
  "Global Partner University 0768",
  "Global Partner University 0769",
  "Global Partner University 0770",
  "Global Partner University 0771",
  "Global Partner University 0772",
  "Global Partner University 0773",
  "Global Partner University 0774",
  "Global Partner University 0775",
  "Global Partner University 0776",
  "Global Partner University 0777",
  "Global Partner University 0778",
  "Global Partner University 0779",
  "Global Partner University 0780",
  "Global Partner University 0781",
  "Global Partner University 0782",
  "Global Partner University 0783",
  "Global Partner University 0784",
  "Global Partner University 0785",
  "Global Partner University 0786",
  "Global Partner University 0787",
  "Global Partner University 0788",
  "Global Partner University 0789",
  "Global Partner University 0790",
  "Global Partner University 0791",
  "Global Partner University 0792",
  "Global Partner University 0793",
  "Global Partner University 0794",
  "Global Partner University 0795",
  "Global Partner University 0796",
  "Global Partner University 0797",
  "Global Partner University 0798",
  "Global Partner University 0799",
  "Global Partner University 0800",
  "Global Partner University 0801",
  "Global Partner University 0802",
  "Global Partner University 0803",
  "Global Partner University 0804",
  "Global Partner University 0805",
  "Global Partner University 0806",
  "Global Partner University 0807",
  "Global Partner University 0808",
  "Global Partner University 0809",
  "Global Partner University 0810",
  "Global Partner University 0811",
  "Global Partner University 0812",
  "Global Partner University 0813",
  "Global Partner University 0814",
  "Global Partner University 0815",
  "Global Partner University 0816",
  "Global Partner University 0817",
  "Global Partner University 0818",
  "Global Partner University 0819",
  "Global Partner University 0820",
  "Global Partner University 0821",
  "Global Partner University 0822",
  "Global Partner University 0823",
  "Global Partner University 0824",
  "Global Partner University 0825",
  "Global Partner University 0826",
  "Global Partner University 0827",
  "Global Partner University 0828",
  "Global Partner University 0829",
  "Global Partner University 0830",
  "Global Partner University 0831",
  "Global Partner University 0832",
  "Global Partner University 0833",
  "Global Partner University 0834",
  "Global Partner University 0835",
  "Global Partner University 0836",
  "Global Partner University 0837",
  "Global Partner University 0838",
  "Global Partner University 0839",
  "Global Partner University 0840",
  "Global Partner University 0841",
  "Global Partner University 0842",
  "Global Partner University 0843",
  "Global Partner University 0844",
  "Global Partner University 0845",
  "Global Partner University 0846",
  "Global Partner University 0847",
  "Global Partner University 0848",
  "Global Partner University 0849",
  "Global Partner University 0850",
  "Global Partner University 0851",
  "Global Partner University 0852",
  "Global Partner University 0853",
  "Global Partner University 0854",
  "Global Partner University 0855",
  "Global Partner University 0856",
  "Global Partner University 0857",
  "Global Partner University 0858",
  "Global Partner University 0859",
  "Global Partner University 0860",
  "Global Partner University 0861",
  "Global Partner University 0862",
  "Global Partner University 0863",
  "Global Partner University 0864",
  "Global Partner University 0865",
  "Global Partner University 0866",
  "Global Partner University 0867",
  "Global Partner University 0868",
  "Global Partner University 0869",
  "Global Partner University 0870",
  "Global Partner University 0871",
  "Global Partner University 0872",
  "Global Partner University 0873",
  "Global Partner University 0874",
  "Global Partner University 0875",
  "Global Partner University 0876",
  "Global Partner University 0877",
  "Global Partner University 0878",
  "Global Partner University 0879",
  "Global Partner University 0880",
  "Global Partner University 0881",
  "Global Partner University 0882",
  "Global Partner University 0883",
  "Global Partner University 0884",
  "Global Partner University 0885",
  "Global Partner University 0886",
  "Global Partner University 0887",
  "Global Partner University 0888",
  "Global Partner University 0889",
  "Global Partner University 0890",
  "Global Partner University 0891",
  "Global Partner University 0892",
  "Global Partner University 0893",
  "Global Partner University 0894",
  "Global Partner University 0895",
  "Global Partner University 0896",
  "Global Partner University 0897",
  "Global Partner University 0898",
  "Global Partner University 0899",
  "Global Partner University 0900",
  "Global Partner University 0901",
  "Global Partner University 0902",
  "Global Partner University 0903",
  "Global Partner University 0904",
  "Global Partner University 0905",
  "Global Partner University 0906",
  "Global Partner University 0907",
  "Global Partner University 0908",
  "Global Partner University 0909",
  "Global Partner University 0910",
  "Global Partner University 0911",
  "Global Partner University 0912",
  "Global Partner University 0913",
  "Global Partner University 0914",
  "Global Partner University 0915",
  "Global Partner University 0916",
  "Global Partner University 0917",
  "Global Partner University 0918",
  "Global Partner University 0919",
  "Global Partner University 0920",
  "Global Partner University 0921",
  "Global Partner University 0922",
  "Global Partner University 0923",
  "Global Partner University 0924",
  "Global Partner University 0925",
  "Global Partner University 0926",
  "Global Partner University 0927",
  "Global Partner University 0928",
  "Global Partner University 0929",
  "Global Partner University 0930",
  "Global Partner University 0931",
  "Global Partner University 0932",
  "Global Partner University 0933",
  "Global Partner University 0934",
  "Global Partner University 0935",
  "Global Partner University 0936",
  "Global Partner University 0937",
  "Global Partner University 0938",
  "Global Partner University 0939",
  "Global Partner University 0940",
  "Global Partner University 0941",
  "Global Partner University 0942",
  "Global Partner University 0943",
  "Global Partner University 0944",
  "Global Partner University 0945",
  "Global Partner University 0946",
  "Global Partner University 0947",
  "Global Partner University 0948",
  "Global Partner University 0949",
  "Global Partner University 0950",
  "Global Partner University 0951",
  "Global Partner University 0952",
  "Global Partner University 0953",
  "Global Partner University 0954",
  "Global Partner University 0955",
  "Global Partner University 0956",
  "Global Partner University 0957",
  "Global Partner University 0958",
  "Global Partner University 0959",
  "Global Partner University 0960",
  "Global Partner University 0961",
  "Global Partner University 0962",
  "Global Partner University 0963",
  "Global Partner University 0964",
  "Global Partner University 0965",
  "Global Partner University 0966",
  "Global Partner University 0967",
  "Global Partner University 0968",
  "Global Partner University 0969",
  "Global Partner University 0970",
  "Global Partner University 0971",
  "Global Partner University 0972",
  "Global Partner University 0973",
  "Global Partner University 0974",
  "Global Partner University 0975",
  "Global Partner University 0976",
  "Global Partner University 0977",
  "Global Partner University 0978",
  "Global Partner University 0979",
  "Global Partner University 0980",
  "Global Partner University 0981",
  "Global Partner University 0982",
  "Global Partner University 0983",
  "Global Partner University 0984",
  "Global Partner University 0985",
  "Global Partner University 0986",
  "Global Partner University 0987",
  "Global Partner University 0988",
  "Global Partner University 0989",
  "Global Partner University 0990",
  "Global Partner University 0991",
  "Global Partner University 0992",
  "Global Partner University 0993",
  "Global Partner University 0994",
  "Global Partner University 0995",
  "Global Partner University 0996",
  "Global Partner University 0997",
  "Global Partner University 0998",
  "Global Partner University 0999",
  "Global Partner University 1000",
  "Global Partner University 1001",
  "Global Partner University 1002",
  "Global Partner University 1003",
  "Global Partner University 1004",
  "Global Partner University 1005",
  "Global Partner University 1006",
  "Global Partner University 1007",
  "Global Partner University 1008",
  "Global Partner University 1009",
  "Global Partner University 1010",
  "Global Partner University 1011",
  "Global Partner University 1012",
  "Global Partner University 1013",
  "Global Partner University 1014",
  "Global Partner University 1015",
  "Global Partner University 1016",
  "Global Partner University 1017",
  "Global Partner University 1018",
  "Global Partner University 1019",
  "Global Partner University 1020",
  "Global Partner University 1021",
  "Global Partner University 1022",
  "Global Partner University 1023",
  "Global Partner University 1024",
  "Global Partner University 1025",
  "Global Partner University 1026",
  "Global Partner University 1027",
  "Global Partner University 1028",
  "Global Partner University 1029",
  "Global Partner University 1030",
  "Global Partner University 1031",
  "Global Partner University 1032",
  "Global Partner University 1033",
  "Global Partner University 1034",
  "Global Partner University 1035",
  "Global Partner University 1036",
  "Global Partner University 1037",
  "Global Partner University 1038",
  "Global Partner University 1039",
  "Global Partner University 1040",
  "Global Partner University 1041",
  "Global Partner University 1042",
  "Global Partner University 1043",
  "Global Partner University 1044",
  "Global Partner University 1045",
  "Global Partner University 1046",
  "Global Partner University 1047",
  "Global Partner University 1048",
  "Global Partner University 1049",
  "Global Partner University 1050",
  "Global Partner University 1051",
  "Global Partner University 1052",
  "Global Partner University 1053",
  "Global Partner University 1054",
  "Global Partner University 1055",
  "Global Partner University 1056",
  "Global Partner University 1057",
  "Global Partner University 1058",
  "Global Partner University 1059",
  "Global Partner University 1060",
  "Global Partner University 1061",
  "Global Partner University 1062",
  "Global Partner University 1063",
  "Global Partner University 1064",
  "Global Partner University 1065",
  "Global Partner University 1066",
  "Global Partner University 1067",
  "Global Partner University 1068",
  "Global Partner University 1069",
  "Global Partner University 1070",
  "Global Partner University 1071",
  "Global Partner University 1072",
  "Global Partner University 1073",
  "Global Partner University 1074",
  "Global Partner University 1075",
  "Global Partner University 1076",
  "Global Partner University 1077",
  "Global Partner University 1078",
  "Global Partner University 1079",
  "Global Partner University 1080",
  "Global Partner University 1081",
  "Global Partner University 1082",
  "Global Partner University 1083",
  "Global Partner University 1084",
  "Global Partner University 1085",
  "Global Partner University 1086",
  "Global Partner University 1087",
  "Global Partner University 1088",
  "Global Partner University 1089",
  "Global Partner University 1090",
  "Global Partner University 1091",
  "Global Partner University 1092",
  "Global Partner University 1093",
  "Global Partner University 1094",
  "Global Partner University 1095",
  "Global Partner University 1096",
  "Global Partner University 1097",
  "Global Partner University 1098",
  "Global Partner University 1099",
  "Global Partner University 1100",
  "Global Partner University 1101",
  "Global Partner University 1102",
  "Global Partner University 1103",
  "Global Partner University 1104",
  "Global Partner University 1105",
  "Global Partner University 1106",
  "Global Partner University 1107",
  "Global Partner University 1108",
  "Global Partner University 1109",
  "Global Partner University 1110",
  "Global Partner University 1111",
  "Global Partner University 1112",
  "Global Partner University 1113",
  "Global Partner University 1114",
  "Global Partner University 1115",
  "Global Partner University 1116",
  "Global Partner University 1117",
  "Global Partner University 1118",
  "Global Partner University 1119",
  "Global Partner University 1120",
  "Global Partner University 1121",
  "Global Partner University 1122",
  "Global Partner University 1123",
  "Global Partner University 1124",
  "Global Partner University 1125",
  "Global Partner University 1126",
  "Global Partner University 1127",
  "Global Partner University 1128",
  "Global Partner University 1129",
  "Global Partner University 1130",
  "Global Partner University 1131",
  "Global Partner University 1132",
  "Global Partner University 1133",
  "Global Partner University 1134",
  "Global Partner University 1135",
  "Global Partner University 1136",
  "Global Partner University 1137",
  "Global Partner University 1138",
  "Global Partner University 1139",
  "Global Partner University 1140",
  "Global Partner University 1141",
  "Global Partner University 1142",
  "Global Partner University 1143",
  "Global Partner University 1144",
  "Global Partner University 1145",
  "Global Partner University 1146",
  "Global Partner University 1147",
  "Global Partner University 1148",
  "Global Partner University 1149",
  "Global Partner University 1150",
  "Global Partner University 1151",
  "Global Partner University 1152",
  "Global Partner University 1153",
  "Global Partner University 1154",
  "Global Partner University 1155",
  "Global Partner University 1156",
  "Global Partner University 1157",
  "Global Partner University 1158",
  "Global Partner University 1159",
  "Global Partner University 1160",
  "Global Partner University 1161",
  "Global Partner University 1162",
  "Global Partner University 1163",
  "Global Partner University 1164",
  "Global Partner University 1165",
  "Global Partner University 1166",
  "Global Partner University 1167",
  "Global Partner University 1168",
  "Global Partner University 1169",
  "Global Partner University 1170",
  "Global Partner University 1171",
  "Global Partner University 1172",
  "Global Partner University 1173",
  "Global Partner University 1174",
  "Global Partner University 1175",
  "Global Partner University 1176",
  "Global Partner University 1177",
  "Global Partner University 1178",
  "Global Partner University 1179",
  "Global Partner University 1180",
  "Global Partner University 1181",
  "Global Partner University 1182",
  "Global Partner University 1183",
  "Global Partner University 1184",
  "Global Partner University 1185",
  "Global Partner University 1186",
  "Global Partner University 1187",
  "Global Partner University 1188",
  "Global Partner University 1189",
  "Global Partner University 1190",
  "Global Partner University 1191",
  "Global Partner University 1192",
  "Global Partner University 1193",
  "Global Partner University 1194",
  "Global Partner University 1195",
  "Global Partner University 1196",
  "Global Partner University 1197",
  "Global Partner University 1198",
  "Global Partner University 1199",
  "Global Partner University 1200",
] as const;

export const LANDING_THEME_SCALE = {
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 18,
    xl: 24,
    pill: 999,
  },
  motion: {
    fast: 160,
    base: 260,
    soft: 420,
    slow: 760,
  },
} as const;
